/* Suhail Sprint 113 — server-timed group challenge. First correct answer advances everyone. */
(function(){
'use strict';
const VERSION='113.0.0',MAX_PLAYERS=10,FIXED_TIME=30;
let pollId=0,tickId=0,currentRoom='',lastState=null,wrongChoice=-1;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const back='<svg viewBox="0 0 24 24"><path d="m9 5 7 7-7 7"/></svg>';
const api=(path,options)=>window.SuhailFriends112.api(path,options);
function ensurePage(){let p=document.getElementById('groupChallengePage');if(!p){p=document.createElement('div');p.id='groupChallengePage';p.className='page';document.querySelector('.content')?.appendChild(p)}return p}
function activate(live=false){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id==='groupChallengePage'));document.querySelector('.content')?.scrollTo?.({top:0});document.body.classList.toggle('s113-live',live);document.querySelectorAll('#s110BottomNav [data-s110-nav]').forEach(b=>b.classList.toggle('active',b.dataset.s110Nav==='account'))}
function stop(){clearInterval(pollId);clearInterval(tickId);pollId=0;tickId=0}
function top(title,sub,backAction="showPage('profilePage')"){return `<div class="s113-top"><button class="s113-back" onclick="${backAction}" aria-label="العودة">${back}</button><div><h1>${esc(title)}</h1><p>${esc(sub)}</p></div><span class="s113-limit">حتى ${MAX_PLAYERS} لاعبين</span></div>`}
function statusText(s){return ({pending:'بانتظار اللاعبين',active:'جارٍ الآن',completed:'مكتمل',invited:'دعوة جديدة',accepted:'مقبول',owner:'المنشئ',declined:'مرفوض'})[s]||s}
function errText(code){return ({at_least_one_friend_required:'اختر صديقًا واحدًا على الأقل',participant_limit:'الحد الأقصى 10 لاعبين شامل منشئ التحدي',accepted_friendship_required:'الدعوة متاحة للأصدقاء المقبولين فقط',at_least_two_players_required:'يجب قبول لاعب واحد على الأقل',insufficient_approved_questions:'لا توجد أسئلة كافية لهذا المسار',authentication_required:'سجّل الدخول مرة أخرى',group_challenge_not_found:'التحدي غير موجود',invite_not_pending:'تم التعامل مع الدعوة مسبقًا'})[code]||'تعذر إكمال العملية الآن'}
window.s113OpenChallenges=async function(){stop();currentRoom='';const p=ensurePage();activate(false);p.innerHTML=`<div class="s113-page">${top('التحديات الجماعية','أول إجابة صحيحة تنقل الجميع للسؤال التالي')}<div class="s113-hero"><h2>تحدٍ سريع وواضح</h2><p>اختر حتى 9 أصدقاء من قائمتك. الوقت ثابت: 30 ثانية لكل سؤال، ولا توجد رسائل أو محادثات.</p><button class="s113-main-btn" onclick="s113OpenCreate()">إنشاء تحدي جديد</button></div><div class="s113-section"><b>تحدياتي</b><span>جار التحميل…</span></div><div class="s113-list"><div class="s113-room">جار تحميل الدعوات…</div></div></div>`;
try{const d=await api('/api/v1/group-challenges');renderList(d.items||[])}catch(e){p.querySelector('.s113-list').innerHTML=`<div class="s112-empty">${esc(errText(e.message))}</div>`}}
function renderList(items){const p=ensurePage(),invited=items.filter(x=>x.my_status==='invited'&&x.status==='pending'),others=items.filter(x=>!(x.my_status==='invited'&&x.status==='pending'));p.innerHTML=`<div class="s113-page">${top('التحديات الجماعية','اختبار فقط — بدون رسائل أو محادثات')}<div class="s113-hero"><h2>أول صحيح يكسب النقطة</h2><p>السؤال يظهر للجميع مع 30 ثانية ثابتة. عند أول إجابة صحيحة يُغلق فورًا وينتقل الجميع.</p><button class="s113-main-btn" onclick="s113OpenCreate()">إنشاء تحدي جديد</button></div>${invited.length?`<div class="s113-section"><b>دعوات جديدة</b><span>${invited.length}</span></div><div class="s113-list">${invited.map(roomCard).join('')}</div>`:''}<div class="s113-section"><b>التحديات</b><span>${others.length}</span></div><div class="s113-list">${others.length?others.map(roomCard).join(''):'<div class="s112-empty">لا توجد تحديات بعد.</div>'}</div></div>`;activate(false)}
function roomCard(r){const actions=r.my_status==='invited'?`<button class="s113-mini-btn primary" onclick="s113Respond('${esc(r.id)}','accept')">قبول</button><button class="s113-mini-btn danger" onclick="s113Respond('${esc(r.id)}','decline')">رفض</button>`:`<button class="s113-mini-btn primary" onclick="s113OpenRoom('${esc(r.id)}')">فتح</button>`;return `<article class="s113-room"><div><b>${esc(r.exam)} • ${Number(r.question_count)} أسئلة</b><span class="s113-status ${esc(r.status)}">${esc(statusText(r.status))}</span><span>${Number(r.accepted_players||1)} من ${Number(r.total_invited||1)} جاهزين • 30 ثانية للسؤال</span></div><div class="s113-room-actions">${actions}</div></article>`}
window.s113Respond=async function(id,action){try{await api(`/api/v1/group-challenges/${id}/respond`,{method:'POST',body:JSON.stringify({action})});action==='accept'?s113OpenRoom(id):s113OpenChallenges()}catch(e){alert(errText(e.message))}};
window.s113OpenCreate=async function(preselect=''){stop();const p=ensurePage();activate(false);p.innerHTML=`<div class="s113-page">${top('إنشاء تحدي','اختر أصدقاءك من القائمة',"s113OpenChallenges()") }<div class="s112-empty">جار تحميل الأصدقاء…</div></div>`;try{const d=await api('/api/v1/friends');renderCreate((d.items||[]).filter(x=>!x.blocked),preselect)}catch(e){p.querySelector('.s112-empty').textContent=errText(e.message)}};
function renderCreate(friends,preselect){const p=ensurePage();p.innerHTML=`<div class="s113-page">${top('إنشاء تحدي','من 2 إلى 10 لاعبين شامل المنشئ',"s113OpenChallenges()") }<div class="s113-form"><section class="s113-field"><label>المسار</label><select id="s113Exam" class="s113-select"><option>قدرات كمي</option><option>قدرات لفظي</option><option>تحصيلي</option></select></section><section class="s113-field"><label>عدد الأسئلة</label><select id="s113Count" class="s113-select"><option value="5">5 أسئلة</option><option value="10" selected>10 أسئلة</option><option value="15">15 سؤالًا</option><option value="20">20 سؤالًا</option></select></section><section class="s113-field"><div class="s113-fixed-time"><div><label style="display:block;font-size:12px;font-weight:950">وقت السؤال</label><span>ثابت للجميع ولا يمكن تغييره</span></div><b>${FIXED_TIME} ثانية</b></div></section><section class="s113-field"><label>الأصدقاء المشاركون <span id="s113Selected" style="font-size:9px;color:var(--s110-muted)">0 / 9</span></label><div class="s113-friend-checks">${friends.length?friends.map(f=>`<label class="s113-check"><input type="checkbox" value="${esc(f.friend_code)}" ${f.friend_code===preselect?'checked':''} onchange="s113CountSelected()"><div><b>${esc(f.friend_name)}</b><span>@${esc(f.username||f.friend_code)}</span></div></label>`).join(''):'<div class="s112-empty">أضف أصدقاء باليوزر أولًا.</div>'}</div></section><div class="s113-note">تصل دعوة لكل صديق. يمكنك بدء التحدي بعد قبول لاعب واحد على الأقل، وبحد أقصى 10 لاعبين إجمالًا.</div><div id="s113CreateStatus" class="s113-form-status"></div><button class="s113-main-btn" onclick="s113CreateRoom()" ${friends.length?'':'disabled'}>إرسال الدعوات</button></div></div>`;activate(false);s113CountSelected()}
window.s113CountSelected=function(){const boxes=[...document.querySelectorAll('.s113-check input:checked')];if(boxes.length>9)boxes[boxes.length-1].checked=false;const n=document.querySelectorAll('.s113-check input:checked').length,el=document.getElementById('s113Selected');if(el)el.textContent=`${n} / 9`};
window.s113CreateRoom=async function(){const codes=[...document.querySelectorAll('.s113-check input:checked')].map(x=>x.value),status=document.getElementById('s113CreateStatus');if(!codes.length){status.textContent='اختر صديقًا واحدًا على الأقل';return}status.textContent='جار إنشاء التحدي…';try{const d=await api('/api/v1/group-challenges',{method:'POST',body:JSON.stringify({exam:document.getElementById('s113Exam').value,question_count:Number(document.getElementById('s113Count').value),friend_codes:codes})});s113OpenRoom(d.id)}catch(e){status.textContent=errText(e.message)}};
window.s113OpenRoom=async function(id){stop();currentRoom=id;const p=ensurePage();activate(false);p.innerHTML=`<div class="s113-page">${top('غرفة التحدي','جار مزامنة اللاعبين',"s113OpenChallenges()") }<div class="s112-empty">جار التحميل…</div></div>`;try{const s=await api(`/api/v1/group-challenges/${id}/state`);renderState(s);if(s.status==='pending'||s.status==='active')startPoll()}catch(e){p.querySelector('.s112-empty').textContent=errText(e.message)}};
function startPoll(){clearInterval(pollId);pollId=setInterval(async()=>{if(!currentRoom)return;try{const s=await api(`/api/v1/group-challenges/${currentRoom}/state`);renderState(s)}catch(_){}},700)}
function renderState(s){lastState=s;if(s.status==='active')return renderLive(s);if(s.status==='completed')return renderFinal(s);renderLobby(s)}
function renderLobby(s){activate(false);const p=ensurePage(),ready=s.members.filter(m=>['owner','accepted'].includes(m.status)).length;p.innerHTML=`<div class="s113-page">${top('غرفة التحدي',`${esc(s.exam)} • ${Number(s.question_count)} أسئلة`,"s113OpenChallenges()") }<section class="s113-lobby"><div class="s113-lobby-head"><b>اللاعبون</b><span class="s113-code">${esc(s.id)}</span></div><div class="s113-members">${s.members.map(m=>`<div class="s113-member"><div><b>${esc(m.display_name)}</b><span>@${esc(m.username||m.friend_code)}</span></div><em class="${['owner','accepted'].includes(m.status)?'ready':''}">${esc(statusText(m.status))}</em></div>`).join('')}</div>${s.is_owner?`<button class="s113-main-btn" onclick="s113StartRoom()" ${ready<2?'disabled':''}>بدء التحدي (${ready} جاهزين)</button>`:`<div class="s113-wait">بانتظار منشئ التحدي لبدء الاختبار.</div>`}</section><div class="s113-note" style="margin-top:10px;text-align:center">وقت كل سؤال ثابت 30 ثانية. أول إجابة صحيحة تنقل الجميع مباشرة.</div></div>`}
window.s113StartRoom=async function(){try{await api(`/api/v1/group-challenges/${currentRoom}/start`,{method:'POST',body:'{}'});const s=await api(`/api/v1/group-challenges/${currentRoom}/state`);renderState(s);startPoll()}catch(e){alert(errText(e.message))}};
function motivation(sec){if(sec<=5)return 'احسم إجابتك';if(sec<=10)return 'راجع المطلوب بسرعة';if(sec<=20)return 'الدقة أولًا ثم السرعة';return 'اقرأ المطلوب أولًا وحافظ على إيقاعك'}
function renderLive(s){activate(true);wrongChoice=-1;const p=ensurePage(),q=s.question||{},options=Array.isArray(q.options)?q.options:[],sec=Math.max(0,Math.ceil(Number(s.remaining_ms||0)/1000)),pct=Math.max(0,Math.min(100,Number(s.remaining_ms||0)/(s.question_time_sec*1000)*100));p.innerHTML=`<div class="s113-page live"><div class="s113-live-top"><button class="s113-back" onclick="s113LeaveLive()" aria-label="الخروج">${back}</button><div class="s113-round"><b>السؤال ${Number(s.current_number)} من ${Number(s.question_count)}</b><span>${esc(s.exam)}</span></div><div class="s113-timer ${sec<=10?'urgent':''}" id="s113Timer" style="--time:${pct}"><b id="s113Seconds">${sec}</b></div></div>${s.last_event?`<div class="s113-event ${s.last_event==='timeout'?'timeout':''}">${s.last_event==='correct'?`${esc(s.last_winner_name||'أحد اللاعبين')} أجاب أولًا بشكل صحيح`:'انتهى وقت السؤال السابق دون نقطة'}</div>`:''}<div class="s113-motivation ${sec<=10?'urgent':''}" id="s113Motivation">${motivation(sec)}</div><section class="s113-question"><h2>${esc(q.question||'جار تحميل السؤال…')}</h2><div class="s113-options">${options.map((o,i)=>`<button class="s113-option" data-index="${i}" onclick="s113Answer(${i})" ${s.already_answered?'disabled':''}><i>${['أ','ب','ج','د'][i]||i+1}</i><span>${esc(o)}</span></button>`).join('')}</div><div class="s113-answer-note" id="s113AnswerNote">${s.already_answered?'تم اعتماد إجابتك؛ بانتظار أول إجابة صحيحة.':'اختر إجابة واحدة فقط'}</div></section>${scoreboard(s.members)}</div>`;startTick(s)}
function startTick(s){clearInterval(tickId);let remaining=Number(s.remaining_ms||0),last=performance.now();tickId=setInterval(()=>{const now=performance.now();remaining=Math.max(0,remaining-(now-last));last=now;const sec=Math.ceil(remaining/1000),pct=remaining/(s.question_time_sec*1000)*100,timer=document.getElementById('s113Timer'),seconds=document.getElementById('s113Seconds'),msg=document.getElementById('s113Motivation');if(seconds)seconds.textContent=sec;if(timer){timer.style.setProperty('--time',pct);timer.classList.toggle('urgent',sec<=10)}if(msg){msg.textContent=motivation(sec);msg.classList.toggle('urgent',sec<=10)}if(remaining<=0)clearInterval(tickId)},120)}
function scoreboard(members){return `<section class="s113-scoreboard"><div class="s113-scoreboard-head"><b>الترتيب المباشر</b><span>النقاط ثم سرعة الإجابات الصحيحة</span></div>${members.filter(m=>['owner','accepted'].includes(m.status)).map((m,i)=>`<div class="s113-rank"><i>${i+1}</i><b>${esc(m.display_name)}</b><strong>${Number(m.score)} نقطة</strong></div>`).join('')}</section>`}
window.s113Answer=async function(index){if(!lastState||lastState.already_answered)return;document.querySelectorAll('.s113-option').forEach(b=>b.disabled=true);const note=document.getElementById('s113AnswerNote');if(note)note.textContent='جار اعتماد الإجابة…';try{const d=await api(`/api/v1/group-challenges/${currentRoom}/answer`,{method:'POST',body:JSON.stringify({selected_index:index,question_index:lastState.current_index})});if(!d.correct){const btn=document.querySelector(`.s113-option[data-index="${index}"]`);btn?.classList.add('wrong');if(note)note.textContent='إجابة غير صحيحة؛ انتظر انتقال المجموعة.'}else if(note)note.textContent='إجابة صحيحة — حصلت على النقطة';renderState(d.state)}catch(e){if(e.data?.state)renderState(e.data.state);else{if(note)note.textContent=errText(e.message)}}};
window.s113LeaveLive=function(){if(confirm('الخروج من الشاشة لا يلغي مشاركتك. يمكنك العودة من قائمة التحديات.')){stop();s113OpenChallenges()}};
function renderFinal(s){stop();activate(false);saveHistory(s);const active=s.members.filter(m=>['owner','accepted'].includes(m.status)),me=active.find(m=>String(m.user_id)===String(s.my_user_id)),avgMs=me&&me.correct_count?Math.round(me.total_response_ms/me.correct_count):0,rating=!avgMs?'لا توجد إجابات صحيحة':avgMs<=10000?'ممتازة':avgMs<=18000?'متوازنة':'تحتاج تحسين',tip=!avgMs?'ابدأ بالدقة ثم ارفع السرعة تدريجيًا.':avgMs<=10000?'سرعتك ممتازة؛ حافظ على الدقة.':avgMs<=18000?'إدارتك للوقت متوازنة؛ حاول حسم الأسئلة الواضحة أسرع.':'متوسطك مرتفع؛ اقرأ المطلوب أولًا وحدد الكلمات المفتاحية.';const p=ensurePage();p.innerHTML=`<div class="s113-page">${top('نتيجة التحدي',`${esc(s.exam)} • ${Number(s.question_count)} أسئلة`,"s113OpenChallenges()") }<section class="s113-final"><h2>${active[0]?`${esc(active[0].display_name)} في المركز الأول`:'انتهى التحدي'}</h2><p>الترتيب حسب النقاط، وعند التعادل حسب إجمالي زمن الإجابات الصحيحة.</p><div class="s113-podium">${active.map((m,i)=>`<div class="s113-final-row"><i>${i+1}</i><div><b>${esc(m.display_name)}</b><span>${Number(m.correct_count)} إجابات حاسمة • ${m.correct_count?Math.round(m.total_response_ms/m.correct_count/1000):'—'} ث/إجابة</span></div><strong>${Number(m.score)}</strong></div>`).join('')}</div><div class="s113-time-rating"><b>إدارة وقتك: ${esc(rating)}</b><span>${esc(tip)}</span></div><button class="s113-main-btn" onclick="s113OpenChallenges()">العودة للتحديات</button></section></div>`}
function saveHistory(s){try{const key='suhail_group_challenge_history',rows=JSON.parse(localStorage.getItem(key)||'[]');if(!rows.some(x=>x.id===s.id)){const active=(s.members||[]).filter(m=>['owner','accepted'].includes(m.status)),index=active.findIndex(m=>String(m.user_id)===String(s.my_user_id)),me=index>=0?active[index]:null;rows.unshift({id:s.id,exam:s.exam,date:new Date().toISOString(),players:active.length,rank:index>=0?index+1:null,score:Number(me?.score||0),correct:Number(me?.correct_count||0),avgMs:me?.correct_count?Math.round(Number(me.total_response_ms||0)/Number(me.correct_count)):0});localStorage.setItem(key,JSON.stringify(rows.slice(0,30)))}}catch(_){}}
window.SuhailGroupChallenge113={version:VERSION,open:window.s113OpenChallenges,maximumPlayers:MAX_PLAYERS,questionTimeSec:FIXED_TIME};window.SUHAIL_RELEASE=VERSION;document.documentElement.dataset.suhailRelease=VERSION;
})();
