/* Suhail Sprints 48-54
   Final UI ownership, explicit navigation modes, independent Qudrat/Tahsili
   diagnostics, multi-goal profile, live streak rescue, deep admin and QA hooks. */
(function(){
  'use strict';
  const VERSION='58.0.0';
  const DAY=86400000;
  const DEFAULT_ADMIN=__S54_ADMIN_SETTINGS__;
  const AVATAR_CATALOG=__S54_AVATARS__;
  const AVATAR_ASSETS=__S54_AVATAR_ASSETS__;
  const AVATAR_PORTRAITS=__S54_AVATAR_PORTRAIT_ASSETS__;
  const AVATAR_HALVES=__S54_AVATAR_HALF_ASSETS__;
  const AVATAR_FULLS=__S54_AVATAR_FULL_ASSETS__;
  const SCORE_CATALOG=__S54_SCORE_MODELS__;
  const CHALLENGE_CATALOG=__S54_CHALLENGES__;
  const CUSTOM_PAGES=new Set(['studentSetupPage','diagnosticChoicePage','s54DiagnosticPage','adminSettingsPage','challengePage']);
  const MAIN_PAGES=new Set(['homePage','reviewPage','summariesPage','tasksPage','statsPage','profilePage','studentSetupPage','diagnosticChoicePage','adminSettingsPage','challengePage','savedQuestionsPage']);
  let legacyShowPage=null;
  let diagnosticState=null;
  let setupDraft=null;
  let navMode='main';
  let adminTab='overview';
  let adminDraftDirty=false;
  let guardBusy=false;

  function esc(v){return String(v==null?'':v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  function parse(raw,fallback){try{return JSON.parse(raw);}catch(_){return fallback;}}
  function clone(v){return parse(JSON.stringify(v),{});}
  function merge(base,override){const out=Array.isArray(base)?base.slice():{...(base||{})};Object.entries(override||{}).forEach(([k,v])=>{if(v&&typeof v==='object'&&!Array.isArray(v)&&out[k]&&typeof out[k]==='object'&&!Array.isArray(out[k]))out[k]=merge(out[k],v);else out[k]=v;});return out;}
  function session(){try{return typeof getAuthSession==='function'?getAuthSession():null;}catch(_){return null;}}
  function isAdmin(){const s=session();return !!(s&&s.role==='admin');}
  function userId(){const s=session();const raw=(s&&s.email?String(s.email):'guest').toLowerCase();return raw.replace(/[^a-z0-9]/g,'_')||'guest';}
  function key(name){return `s54_${name}_${userId()}`;}
  function read(name,fallback){return parse(localStorage.getItem(key(name))||'',fallback);}
  function write(name,value){localStorage.setItem(key(name),JSON.stringify(value));return value;}
  function today(date){const d=date||new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
  function pct(a,b){return b?Math.round(Number(a||0)/Number(b)*100):0;}
  function clamp(n,min,max){return Math.max(min,Math.min(max,Number(n||0)));}
  function avg(xs){return xs.length?xs.reduce((a,b)=>a+Number(b||0),0)/xs.length:0;}
  function hash(text){let h=2166136261;for(const c of String(text)){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;}
  function getPath(obj,path){return String(path).split('.').reduce((a,p)=>a==null?undefined:a[p],obj);}
  function setPath(obj,path,value){const parts=String(path).split('.');let cur=obj;parts.slice(0,-1).forEach(p=>{if(!cur[p]||typeof cur[p]!=='object')cur[p]={};cur=cur[p];});cur[parts.at(-1)]=value;return obj;}
  function toast(message){let el=document.getElementById('s54Toast');if(!el){el=document.createElement('div');el.id='s54Toast';el.className='s54-toast';(document.querySelector('.screen')||document.body).appendChild(el);}el.textContent=message;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),1900);}
  function ensurePage(id){let p=document.getElementById(id);if(!p){p=document.createElement('div');p.id=id;p.className='page';document.querySelector('.content')?.appendChild(p);}return p;}
  function activate(id){if(typeof activatePage==='function')activatePage(id);else{document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));ensurePage(id).classList.add('active');}requestAnimationFrame(()=>setMode(modeForPage(id)));}
  function activePage(){return document.querySelector('.page.active');}

  function svg(name){
    const m={
      home:'<svg viewBox="0 0 24 24"><path d="M3 11.2 12 4l9 7.2V20a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1Z"/></svg>',
      review:'<svg viewBox="0 0 24 24"><path d="M5 4h12a2 2 0 0 1 2 2v14H8a3 3 0 0 1-3-3Z"/><path d="M5 17a3 3 0 0 1 3-3h11M9 8h6"/></svg>',
      summaries:'<svg viewBox="0 0 24 24"><path d="M6 3h9l3 3v15H6Z"/><path d="M15 3v4h4M9 12h6M9 16h6"/></svg>',
      tasks:'<svg viewBox="0 0 24 24"><rect x="4" y="4" width="16" height="17" rx="3"/><path d="M8 9h8M8 14h5m2 2 1.5 1.5L20 14"/></svg>',
      profile:'<svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></svg>',
      back:'<svg viewBox="0 0 24 24"><path d="m9 18 6-6-6-6"/></svg>',
      up:'<svg viewBox="0 0 24 24"><path d="m6 15 6-6 6 6"/></svg>',
      check:'<svg viewBox="0 0 24 24"><path d="m5 12 4 4L19 6"/></svg>',
      bell:'<svg viewBox="0 0 24 24"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></svg>',
      target:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="3"/><path d="m14 10 6-6M16 4h4v4"/></svg>',
      atom:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="1.5"/><ellipse cx="12" cy="12" rx="9" ry="4"/><ellipse cx="12" cy="12" rx="4" ry="9" transform="rotate(35 12 12)"/><ellipse cx="12" cy="12" rx="4" ry="9" transform="rotate(-35 12 12)"/></svg>',
      trophy:'<svg viewBox="0 0 24 24"><path d="M8 4h8v5a4 4 0 0 1-8 0Z"/><path d="M8 6H5v2a3 3 0 0 0 3 3M16 6h3v2a3 3 0 0 1-3 3M12 13v4M8 21h8M9 17h6"/></svg>',
      edit:'<svg viewBox="0 0 24 24"><path d="M4 20h4L19 9l-4-4L4 16Z"/><path d="m13 7 4 4"/></svg>',
      settings:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/><path d="M19 14a2 2 0 0 0 .4 2.2l.1.1-2.2 2.2-.1-.1A2 2 0 0 0 15 18l-.5.2V21h-3v-2.8L11 18a2 2 0 0 0-2.2.4l-.1.1-2.2-2.2.1-.1A2 2 0 0 0 7 14l-.2-.5H4v-3h2.8L7 10a2 2 0 0 0-.4-2.2l-.1-.1 2.2-2.2.1.1A2 2 0 0 0 11 6l.5-.2V3h3v2.8L15 6a2 2 0 0 0 2.2-.4l.1-.1 2.2 2.2-.1.1A2 2 0 0 0 19 10l.2.5H22v3h-2.8Z"/></svg>',
      fire:'<svg viewBox="0 0 24 24" aria-hidden="true"><defs><linearGradient id="s54fire" x1="4" y1="3" x2="19" y2="21"><stop stop-color="#ffb52e"/><stop offset=".55" stop-color="#ff7026"/><stop offset="1" stop-color="#e53c31"/></linearGradient></defs><path fill="url(#s54fire)" stroke="none" d="M13.7 2.4c.7 3.4-.9 4.7-2.1 6.1-.9 1-1.1 2.1-.4 3.3.7-1.4 1.9-2.2 3.1-3.1 2.2 1.8 4.2 4.2 4.2 7.2A6.5 6.5 0 0 1 12 22a6.5 6.5 0 0 1-6.5-6.1c0-3.9 2.7-6.9 5.4-9.5.2 2.3 1.2 2.5 1.8 1.5.8-1.4.2-3.4 1-5.5Z"/><path fill="#ffd75b" stroke="none" d="M12 12.1c1.9 1.6 2.9 2.8 2.9 4.6A2.9 2.9 0 0 1 12 19.6a2.9 2.9 0 0 1-2.9-2.9c0-1.5.9-2.8 2-3.9.1 1.4.6 1.6.9 1 .4-.6.1-1.2 0-1.7Z"/></svg>',
      hourglass:'<svg viewBox="0 0 24 24" aria-hidden="true"><path fill="none" stroke="#e39218" stroke-width="2" stroke-linecap="round" d="M7 3h10M7 21h10M8 4c0 4 1.3 5.5 4 8-2.7 2.5-4 4-4 8M16 4c0 4-1.3 5.5-4 8 2.7 2.5 4 4 4 8"/><path fill="#ffc34c" stroke="none" d="M9.5 7h5c-.5 1.5-1.3 2.4-2.5 3.6C10.8 9.4 10 8.5 9.5 7Zm.2 11c.4-1.4 1.2-2.4 2.3-3.5 1.1 1.1 1.9 2.1 2.3 3.5H9.7Z"/></svg>'
    };return m[name]||m.home;
  }
  function topbar(title,subtitle,action){return `<div class="s54-topbar"><div><div class="s54-title">${esc(title)}</div>${subtitle?`<div class="s54-subtitle">${esc(subtitle)}</div>`:''}</div><button class="s54-back" onclick="${action||"showPage('homePage')"}" aria-label="العودة">${svg('back')}</button></div>`;}

  /* Profile: a learner may prepare for Qudrat, Tahsili, or both.
     Academic track only changes Qudrat. It never changes Tahsili. */
  function oldProfile(){return parse(localStorage.getItem(`s47_profile_${userId()}`)||'',{});}
  function normalizeGender(value,avatarId){if(value==='female'||value==='male')return value;return String(avatarId||'').startsWith('female_')?'female':'male';}
  function defaultAvatarFor(gender){const item=avatarItems(gender)[0];return item?.id||(gender==='female'?'female_01':(AVATAR_CATALOG.default||'male_02'));}
  function defaultProfile(){const s=session()||{};const gender=normalizeGender(s.gender,s.avatarId);return {displayName:s.name||'طالب سهيل',gender,academicTrack:'scientific',examGoals:['qudrat','tahsili'],avatarId:defaultAvatarFor(gender),onboardingDone:false,updatedAt:Date.now()};}
  function normalizeGoals(value){const raw=Array.isArray(value)?value:[value];const out=[...new Set(raw.filter(x=>x==='qudrat'||x==='tahsili'))];return out.length?out:['qudrat'];}
  function getProfile(){let stored=read('profile',null);if(!stored){const old=oldProfile();if(old&&Object.keys(old).length){stored={...old,examGoals:normalizeGoals(old.examGoals||old.targetExam)};write('profile',stored);}}const p=merge(defaultProfile(),stored||{});p.examGoals=normalizeGoals(p.examGoals);p.gender=normalizeGender(p.gender,p.avatarId);if(!avatarItems(p.gender).some(a=>a.id===p.avatarId))p.avatarId=defaultAvatarFor(p.gender);return p;}
  function saveProfile(value){const current=getProfile();const gender=normalizeGender((value||{}).gender,(value||{}).avatarId||current.avatarId);let avatarId=(value||{}).avatarId||current.avatarId;if(!avatarItems(gender).some(a=>a.id===avatarId))avatarId=defaultAvatarFor(gender);const p={...current,...(value||{}),gender,avatarId,examGoals:normalizeGoals((value||{}).examGoals||current.examGoals),onboardingDone:true,updatedAt:Date.now()};delete p.targetExam;write('profile',p);try{const s=session();if(s&&typeof setAuthSession==='function')setAuthSession({...s,name:p.displayName||s.name,gender:p.gender});}catch(_){}return p;}
  function trackLabel(t){return t==='literary'?'أدبي':'علمي';}
  function goalsLabel(gs){const g=normalizeGoals(gs);return g.length===2?'قدرات وتحصيلي':g[0]==='tahsili'?'تحصيلي':'قدرات';}
  function genderLabel(g){return g==='female'?'بنت':'ولد';}
  function avatarItems(gender){const items=Array.isArray(AVATAR_CATALOG.items)?AVATAR_CATALOG.items.filter(x=>x.enabled!==false):[];return gender?items.filter(x=>(x.gender_key||String(x.id).split('_')[0])===gender):items;}
  function avatarSrc(id,variant='portrait'){const maps={card:AVATAR_ASSETS,portrait:AVATAR_PORTRAITS,half:AVATAR_HALVES,full:AVATAR_FULLS};const source=maps[variant]||AVATAR_PORTRAITS;return source[id]||source[AVATAR_CATALOG.default]||AVATAR_ASSETS[id]||'';}
  function avatarHtml(p,variant='portrait'){return `<div class="s54-avatar"><img src="${avatarSrc(p.avatarId,variant)}" alt="${esc(p.displayName)}"></div>`;}
  function friendCode(){return `SH-${String(hash(userId())).slice(-6).padStart(6,'0')}`;}

  function adminSettings(){return merge(clone(DEFAULT_ADMIN),parse(localStorage.getItem('s54_admin_settings')||'',{}));}
  function saveAdminSettings(v){localStorage.setItem('s54_admin_settings',JSON.stringify(v));return v;}

  /* Explicit navigation contract: no CSS-class inference. */
  function navItems(){return [
    {id:'review',label:'المراجعة',icon:'review',action:"showPage('reviewPage')",pages:['reviewPage','errorReviewPage']},
    {id:'summaries',label:'الملخصات',icon:'summaries',action:"s28SummariesGateway()",pages:['summariesPage','skillHubPage']},
    {id:'home',label:'الرئيسية',icon:'home',action:"showPage('homePage')",pages:['homePage']},
    {id:'tasks',label:'المهام',icon:'tasks',action:"showPage('tasksPage')",pages:['tasksPage','statsPage']},
    {id:'profile',label:'الحساب',icon:'profile',action:"showPage('profilePage')",pages:['profilePage','studentSetupPage','adminSettingsPage','challengePage','questionManagementPage','aiGeneratorPage']}
  ];}
  function navButtons(lift){return navItems().map(x=>`<button class="s54-nav-btn ${x.id==='home'?'home':''}" data-s54-nav="${x.id}" onclick="${x.action};document.body.classList.remove('s54-lift-open')"><span class="s54-nav-icon">${svg(x.icon)}</span><span>${x.label}</span></button>`).join('');}
  function ensureNav(){const screen=document.querySelector('.screen');if(!screen)return;let nav=document.getElementById('s54BottomNav');if(!nav){nav=document.createElement('nav');nav.id='s54BottomNav';nav.className='s54-bottom-nav';nav.setAttribute('aria-label','القائمة الرئيسية');nav.innerHTML=navButtons(false);screen.appendChild(nav);}let lift=document.getElementById('s54LiftNav');if(!lift){lift=document.createElement('div');lift.id='s54LiftNav';lift.className='s54-lift-nav';lift.innerHTML=`<div class="s54-lift-shade" onclick="document.body.classList.remove('s54-lift-open')"></div><button class="s54-lift-handle" onclick="document.body.classList.toggle('s54-lift-open')" aria-label="إظهار القائمة">${svg('up')}</button><div class="s54-lift-panel">${navButtons(true)}</div>`;screen.appendChild(lift);}}
  function modeForPage(id){if(id==='s54DiagnosticPage'&&diagnosticState&&!diagnosticState.finished)return'exam';if(id==='exercisePage'&&typeof isExamInProgress==='function'&&isExamInProgress())return'exam';return'main';}
  function authVisible(){const el=document.getElementById('authPage');return !!(el&&el.classList.contains('active'));}
  function syncAuthMode(){document.body.classList.toggle('s54-auth-mode',authVisible());}
  function setMode(mode){navMode=['main','summary','exam'].includes(mode)?mode:'main';document.body.classList.toggle('s54-mode-main',navMode==='main');document.body.classList.toggle('s54-mode-summary',navMode==='summary');document.body.classList.toggle('s54-mode-exam',navMode==='exam');if(navMode!=='summary')document.body.classList.remove('s54-lift-open');ensureNav();refreshNavActive();syncAuthMode();}
  function refreshNavActive(){const id=activePage()?.id||'homePage';document.querySelectorAll('#s54BottomNav .s54-nav-btn').forEach(b=>b.classList.remove('active'));const item=navItems().find(x=>x.pages.includes(id));if(item)document.querySelector(`#s54BottomNav [data-s54-nav="${item.id}"]`)?.classList.add('active');}

  /* Activity and live streak. */
  function activity(){let data=read('activity',null);if(!data){const old=parse(localStorage.getItem(`s47_activity_${userId()}`)||'',null);data=old||{dates:[],events:[],lastAt:0};write('activity',data);}return merge({dates:[],events:[],lastAt:0},data);}
  function markActivity(type){const d=activity();const day=today();if(!d.dates.includes(day))d.dates.push(day);d.events.push({type:type||'learning',at:Date.now()});d.events=d.events.slice(-400);d.dates=d.dates.slice(-500);d.lastAt=Date.now();write('activity',d);updateStreakElements();}
  function streakStatus(){const d=activity();const set=new Set(d.dates||[]);const now=new Date();const hasToday=set.has(today(now));let cursor=new Date(now.getFullYear(),now.getMonth(),now.getDate());if(!hasToday)cursor=new Date(cursor.getTime()-DAY);let count=0;for(let i=0;i<500;i++){if(!set.has(today(cursor)))break;count++;cursor=new Date(cursor.getTime()-DAY);}const midnight=new Date(now.getFullYear(),now.getMonth(),now.getDate()+1);const msLeft=Math.max(0,midnight-now);const rescue=Number(adminSettings().streak?.rescue_window_hours||6);return {count,hasToday,risk:!hasToday&&count>0&&msLeft<=rescue*3600000,msLeft,hoursLeft:msLeft/3600000};}
  function timeLeft(ms){const h=Math.floor(ms/3600000),m=Math.floor(ms%3600000/60000);return `${h}:${String(m).padStart(2,'0')}`;}
  function streakMarkup(s){return `${s.risk?svg('hourglass'):svg('fire')}<span class="s54-streak-count">${s.count}</span>`;}
  function updateStreakElements(){const s=streakStatus();document.querySelectorAll('.s54-streak').forEach(el=>{el.classList.toggle('risk',s.risk);el.innerHTML=streakMarkup(s);el.title=s.risk?`باقي ${timeLeft(s.msLeft)}`:'السلسلة اليومية';});document.querySelectorAll('[data-s54-streak-text]').forEach(el=>{el.textContent=s.risk?`باقي ${timeLeft(s.msLeft)} قبل انقطاع السلسلة`:s.hasToday?'تم تثبيت إنجاز اليوم':s.count?'أكمل نشاطًا اليوم':'ابدأ أول يوم';});}
  window.s54StreakInfo=function(){const s=streakStatus();toast(s.risk?`⌛ بقي ${timeLeft(s.msLeft)}: أكمل نشاطًا لحفظ ${s.count} أيام`:(s.hasToday?`تم حفظ سلسلة ${s.count} أيام اليوم`:(s.count?`نفّذ سؤالًا أو افتح ملخصًا لحفظ ${s.count} أيام`:'ابدأ أول نشاط تعليمي اليوم')));};

  function history(){try{return typeof getExamHistory==='function'?getExamHistory():[];}catch(_){return[];}}
  function diagnostics(){let d=read('diagnostics',null);if(!d){const old=parse(localStorage.getItem(`s47_diagnostics_${userId()}`)||'',{});d=old||{};write('diagnostics',d);}return d||{};}
  function predictionFor(path){const record=diagnostics()[path];const rows=history().filter(r=>path==='qudrat'?String(r.exam||'').includes('قدرات'):String(r.exam||'')==='تحصيلي').slice(-10);const vals=[];if(record)vals.push(Number(record.weightedPercent||0));rows.forEach(r=>vals.push(Number(r.percent||0)));if(!vals.length)return{ready:false,low:0,high:0,center:0,label:'ابدأ القياس'};let weighted=0,w=0;vals.forEach((v,i)=>{const k=i+1;weighted+=v*k;w+=k;});let center=weighted/w;const times=rows.map(r=>Number(r.avgSec||60));if(times.length&&avg(times)<50)center+=1;if(times.length&&avg(times)>80)center-=1.5;const width=vals.length>=8?3:vals.length>=4?5:7;center=Math.round(clamp(center,0,100));return{ready:true,center,low:Math.round(clamp(center-width,0,100)),high:Math.round(clamp(center+width,0,100)),label:vals.length>=8?'ثقة مرتفعة':vals.length>=4?'ثقة متوسطة':'تقدير أولي'};}
  function planProgress(){const old=parse(localStorage.getItem(`s39_daily_plans_${userId()}`)||'',{});const d=old[today()]||{};const ids=['diagnostic','practice','errors','mastery','summary'];return{done:ids.filter(x=>!!d[x]).length,total:ids.length};}
  function nextPendingGoal(p){const ds=diagnostics();return p.examGoals.find(g=>!ds[g])||p.examGoals[0]||'qudrat';}

  function renderHome(){const page=document.getElementById('homePage');if(!page)return;guardBusy=true;const p=getProfile(),ds=diagnostics(),plan=planProgress(),planPct=pct(plan.done,plan.total),st=streakStatus();const pending=nextPendingGoal(p);const allMeasured=p.examGoals.every(g=>!!ds[g]);const qp=predictionFor('qudrat'),tp=predictionFor('tahsili');const readiness=[qp.ready?`${qp.low}–${qp.high}`:'—',tp.ready?`${tp.low}–${tp.high}`:'—'];const primary=allMeasured?`showPage('tasksPage')`:`s54OpenDiagnostic('${pending}')`;const primaryText=allMeasured?'ابدأ جلسة اليوم':pending==='qudrat'?'ابدأ تحديد مستوى القدرات':'ابدأ تحديد مستوى التحصيلي';
    page.innerHTML=`<div class="s54-home" data-s54-home="1">
      <div class="s54-home-head"><div class="s54-user">${avatarHtml(p)}<div><b>هلا ${esc(String(p.displayName||'يا بطل').split(' ')[0])}</b><span>${goalsLabel(p.examGoals)}${p.examGoals.includes('qudrat')?` • ${trackLabel(p.academicTrack)} للقدرات`:''}</span></div></div><div class="s54-head-actions"><button class="s54-streak ${st.risk?'risk':''}" onclick="s54StreakInfo()">${streakMarkup(st)}</button><button class="s54-icon-btn" onclick="typeof s39EnableReminder==='function'&&s39EnableReminder()">${svg('bell')}</button></div></div>
      <section class="s54-hero"><span class="s54-kicker">سهيل رفيق رحلتك</span><h1>${allMeasured?'اليوم نكمل من مكانك':'نحدد نقطة البداية لكل اختبار'}</h1><p>${allMeasured?'سهيل رتّب لك جلسة قصيرة حسب أخطائك وأضعف مهاراتك.':'للقدرات قياس مستقل يتأثر بمسارك العلمي أو الأدبي، وللتحصيلي قياس مستقل واحد لا يتغير بالمسار.'}</p><div class="s54-hero-actions"><button class="s54-primary" onclick="${primary}">${primaryText}</button><button class="s54-secondary" onclick="showPage('studentSetupPage')">تعديل هدفي</button></div></section>
      <div class="s54-kpis"><div class="s54-kpi"><b>${p.examGoals.includes('qudrat')?readiness[0]:'—'}</b><span>جاهزية القدرات</span></div><div class="s54-kpi"><b>${st.count}</b><span data-s54-streak-text>${st.risk?`باقي ${timeLeft(st.msLeft)}`:st.hasToday?'تم إنجاز اليوم':st.count?'نشاط واحد يحفظها':'ابدأ السلسلة'}</span></div><div class="s54-kpi"><b>${planPct}%</b><span>خطة اليوم</span></div></div>
      <div class="s54-today"><div class="s54-today-top"><b>رحلة اليوم</b><span>${plan.done}/${plan.total} خطوات</span></div><div class="s54-progress"><i style="width:${planPct}%"></i></div><div class="s54-today-row"><span>${plan.done===plan.total?'أنجزت خطة اليوم، ممتاز!':`باقي ${plan.total-plan.done} مهام قصيرة`}</span><button onclick="showPage('tasksPage')">افتح الخطة</button></div></div>
      <div class="s54-section"><div class="s54-section-head"><b>مؤشر جاهزيتك</b><button class="s54-link" onclick="showPage('statsPage')">التفاصيل</button></div><div class="s54-readiness-grid">
        <button class="s54-readiness" onclick="s54OpenDiagnostic('qudrat')"><div class="head"><b>القدرات</b><span class="badge">${svg('target')}</span></div><small>${trackLabel(p.academicTrack)}: ${p.academicTrack==='literary'?'4 كمي + 8 لفظي':'6 كمي + 6 لفظي'}. هذا القياس مستقل عن التحصيلي.</small><em>${ds.qudrat?`${ds.qudrat.weightedPercent}% • تحديث القياس`:'ابدأ القياس'}</em></button>
        <button class="s54-readiness tahsili" onclick="s54OpenDiagnostic('tahsili')"><div class="head"><b>التحصيلي</b><span class="badge">${svg('atom')}</span></div><small>رياضيات وفيزياء وكيمياء وأحياء. نفس القياس لجميع الطلاب ولا يعتمد على علمي أو أدبي.</small><em>${ds.tahsili?`${ds.tahsili.weightedPercent}% • تحديث القياس`:'ابدأ القياس'}</em></button>
      </div></div>
      <div class="s54-section"><div class="s54-section-head"><b>تحدي مع صديق</b><button class="s54-link" onclick="showPage('challengePage')">عرض الكل</button></div><div class="s54-challenge-banner"><div><b>حوّل المذاكرة إلى منافسة</b><span>اختر تحديًا قصيرًا، قارن الدقة والوقت، ثم أعد المباراة.</span><button onclick="showPage('challengePage')">ابدأ تحديًا</button></div><div class="s54-trophy">${svg('trophy')}</div></div></div>
    </div>`;guardBusy=false;setMode('main');}

  function renderProfile(){const page=ensurePage('profilePage'),p=getProfile(),st=streakStatus();page.innerHTML=`<div class="s54-page">${topbar('الحساب','إعدادات رحلتك التعليمية',"showPage('homePage')")}<div class="s54-profile-hero">${avatarHtml(p)}<div><b>${esc(p.displayName)}</b><p>${goalsLabel(p.examGoals)}${p.examGoals.includes('qudrat')?` • ${trackLabel(p.academicTrack)} للقدرات`:''} • ${st.count} يوم متتالي</p><span class="s54-code">كود الصداقة: ${friendCode()}</span></div></div><div class="s54-section"><div class="s54-settings"><button class="s54-setting" onclick="showPage('studentSetupPage')"><div class="main"><span class="ico">${svg('edit')}</span><div><b>الاختبارات والمسار والشخصية</b><small>يمكنك اختيار القدرات والتحصيلي معًا؛ المسار يؤثر على القدرات فقط</small></div></div><span class="arrow">‹</span></button><button class="s54-setting" onclick="showPage('diagnosticChoicePage')"><div class="main"><span class="ico">${svg('target')}</span><div><b>تحديد المستوى</b><small>قياسان منفصلان: قدرات وتحـصيلي</small></div></div><span class="arrow">‹</span></button><button class="s54-setting" onclick="showPage('challengePage')"><div class="main"><span class="ico">${svg('trophy')}</span><div><b>الأصدقاء والتحديات</b><small>إضافة صديق، دعوات، وترتيب المنافسات</small></div></div><span class="arrow">‹</span></button>${isAdmin()?`<button class="s54-setting" onclick="showPage('adminSettingsPage')"><div class="main"><span class="ico">${svg('settings')}</span><div><b>لوحة إعدادات الأدمن</b><small>مسودة، نشر، سجل تغييرات، ومزامنة API</small></div></div><span class="arrow">‹</span></button>`:''}</div></div></div>`;setMode('main');}

  function renderSetup(){const page=ensurePage('studentSetupPage');setupDraft=merge(getProfile(),setupDraft||{});setupDraft.gender=normalizeGender(setupDraft.gender,setupDraft.avatarId);if(!avatarItems(setupDraft.gender).some(a=>a.id===setupDraft.avatarId))setupDraft.avatarId=defaultAvatarFor(setupDraft.gender);const p=setupDraft;const visibleAvatars=avatarItems(p.gender);page.innerHTML=`<div class="s54-page">${topbar('إعداد رحلتك','اختباراتك ومسارك وشخصيتك',"showPage('profilePage')")}<div class="s54-section"><div class="s54-section-head"><b>وش تبي تستعد له؟</b></div><div class="s54-choice-grid">${goalChoice('qudrat','القدرات','كمي ولفظي؛ المسار العلمي أو الأدبي يغيّر القياس','target')}${goalChoice('tahsili','التحصيلي','رياضيات وفيزياء وكيمياء وأحياء؛ لا يتغير بالمسار','atom')}</div><div class="s54-note">القدرات والتحصيلي مساران مستقلان داخل حسابك. اختيارك لأحدهما لا يلغي الآخر، ونتائج تحديد المستوى لا تختلط.</div></div><div class="s54-section"><div class="s54-section-head"><b>مسارك للقدرات</b></div><div class="s54-choice-grid">${trackChoice('scientific','علمي','6 كمي + 6 لفظي')}${trackChoice('literary','أدبي','4 كمي + 8 لفظي')}</div><div class="s54-note">هذا الاختيار يستخدم في تحديد مستوى القدرات وحساب مؤشرها فقط. لا يغيّر اختبار التحصيلي أو نتيجته.</div></div><div class="s54-section"><div class="s54-section-head"><b>الحساب</b><span>${genderLabel(p.gender)}</span></div><div class="s54-gender-grid">${genderChoice('male','ولد')}${genderChoice('female','بنت')}</div><div class="s54-note">يعرض سهيل شخصيات الأولاد لحساب الولد، وشخصيات البنات لحساب البنت فقط.</div></div><div class="s54-section s54-character-section"><div class="s54-section-head"><b>اختر شخصيتك</b><span>${visibleAvatars.length} خيارات</span></div><div class="s54-avatar-grid">${visibleAvatars.map(a=>`<button class="s54-avatar-option ${p.avatarId===a.id?'selected':''}" onclick="s54SetupAvatar('${esc(a.id)}')"><span class="s54-avatar-stage"><img src="${avatarSrc(a.id,'card')}" alt="شخصية حساب"></span><i>${svg('check')}</i></button>`).join('')}</div></div><button class="s54-primary" style="width:100%;margin-top:16px" onclick="s54SaveSetup()">حفظ الرحلة</button></div>`;setMode('main');}
  function goalChoice(id,title,desc,ico){const selected=setupDraft.examGoals.includes(id);return `<button class="s54-choice ${selected?'selected':''}" onclick="s54ToggleGoal('${id}')"><span class="check">${svg('check')}</span><span class="icon">${svg(ico)}</span><b>${title}</b><small>${desc}</small></button>`;}
  function trackChoice(id,title,desc){const selected=setupDraft.academicTrack===id;return `<button class="s54-choice ${selected?'selected':''}" onclick="s54SetupTrack('${id}')"><span class="check">${svg('check')}</span><span class="icon">${svg(id==='scientific'?'atom':'summaries')}</span><b>${title}</b><small>${desc}</small></button>`;}
  function genderChoice(id,title){const selected=setupDraft.gender===id;return `<button class="s54-gender-choice ${selected?'selected':''}" onclick="s54SetupGender('${id}')"><span>${id==='male'?'♂':'♀'}</span><b>${title}</b><i>${svg('check')}</i></button>`;}
  window.s54ToggleGoal=function(id){const g=normalizeGoals(setupDraft.examGoals);if(g.includes(id)&&g.length===1){toast('اختر اختبارًا واحدًا على الأقل');return;}setupDraft.examGoals=g.includes(id)?g.filter(x=>x!==id):[...g,id];renderSetup();};
  window.s54SetupTrack=function(id){setupDraft.academicTrack=id;renderSetup();};
  window.s54SetupGender=function(id){if(id!=='male'&&id!=='female')return;setupDraft.gender=id;if(!avatarItems(id).some(a=>a.id===setupDraft.avatarId))setupDraft.avatarId=defaultAvatarFor(id);renderSetup();};
  window.s54SetupAvatar=function(id){const item=avatarItems(setupDraft.gender).find(a=>a.id===id);if(!item){toast('اختر شخصية من خيارات الحساب');return;}setupDraft.avatarId=id;renderSetup();};
  window.s54SaveSetup=function(){saveProfile(setupDraft);setupDraft=null;toast('تم حفظ رحلتك وشخصيتك');showPage('homePage');};

  function diagnosticConfig(path){const cfg=adminSettings().diagnostic||{},p=getProfile();if(path==='qudrat')return p.academicTrack==='literary'?(cfg.qudrat_literary||{quant:4,verbal:8}):(cfg.qudrat_scientific||{quant:6,verbal:6});return cfg.tahsili_common||{math:3,physics:3,chemistry:3,biology:3};}
  function questionBank(){try{return Array.isArray(questions)?questions:[];}catch(_){return[];}}
  function seededPick(items,count,salt){return items.slice().sort((a,b)=>hash(`${a.id||a.question}|${salt}`)-hash(`${b.id||b.question}|${salt}`)).slice(0,Math.max(0,Number(count||0)));}
  function buildDiagnostic(path){const cfg=diagnosticConfig(path),bank=questionBank(),salt=`${userId()}-${path}-${Date.now()}`;let out=[];if(path==='qudrat'){out.push(...seededPick(bank.filter(q=>q.exam==='قدرات كمي'),cfg.quant,salt+'q'));out.push(...seededPick(bank.filter(q=>q.exam==='قدرات لفظي'),cfg.verbal,salt+'v'));}else{[['رياضيات','math'],['فيزياء','physics'],['كيمياء','chemistry'],['أحياء','biology']].forEach(([subject,k])=>out.push(...seededPick(bank.filter(q=>q.exam==='تحصيلي'&&q.subject===subject),cfg[k],salt+subject)));}return out.sort((a,b)=>hash(`${a.id}${salt}mix`)-hash(`${b.id}${salt}mix`));}
  function renderDiagnosticChoice(preferred){const page=ensurePage('diagnosticChoicePage'),p=getProfile(),cfgQ=diagnosticConfig('qudrat'),cfgT=diagnosticConfig('tahsili');page.innerHTML=`<div class="s54-page">${topbar('تحديد المستوى','كل اختبار له قياس ونتيجة مستقلة',"showPage('homePage')")}<div class="s54-diag-intro"><h2>اختر القياس الذي تريد الآن</h2><p>لن نخلط أسئلة القدرات مع التحصيلي. تستطيع تنفيذ أحدهما اليوم والآخر لاحقًا، وتظهر لكل واحد جاهزيته الخاصة.</p><div class="s54-facts"><div class="s54-fact"><b>2</b><span>قياسان مستقلان</span></div><div class="s54-fact"><b>≈10د</b><span>لكل قياس</span></div><div class="s54-fact"><b>مستمر</b><span>يتحدث مع تدريبك</span></div></div></div><div class="s54-section"><div class="s54-choice-grid"><button class="s54-choice ${preferred==='qudrat'?'selected':''}" onclick="s54StartDiagnostic('qudrat')"><span class="icon">${svg('target')}</span><b>تحديد مستوى القدرات</b><small>مسارك ${trackLabel(p.academicTrack)}: ${cfgQ.quant} كمي + ${cfgQ.verbal} لفظي. لا يتضمن أي سؤال تحصيلي.</small></button><button class="s54-choice ${preferred==='tahsili'?'selected':''}" onclick="s54StartDiagnostic('tahsili')"><span class="icon">${svg('atom')}</span><b>تحديد مستوى التحصيلي</b><small>${cfgT.math+cfgT.physics+cfgT.chemistry+cfgT.biology} سؤالًا من المواد الأربع. نفس القياس مهما كان مسار القدرات.</small></button></div></div><div class="s54-note">المسار العلمي أو الأدبي يخص القدرات فقط. التحصيلي في سهيل لا يُقسّم حسب هذا الاختيار.</div></div>`;setMode('main');}
  window.s54OpenDiagnostic=function(path){activate('diagnosticChoicePage');renderDiagnosticChoice(path);};
  window.s54StartDiagnostic=function(path){const items=buildDiagnostic(path);if(!items.length){toast('لا توجد أسئلة كافية لهذا القياس');return;}diagnosticState={path,items,index:0,answers:[],selected:null,startedAt:Date.now(),finished:false};activate('s54DiagnosticPage');renderDiagnosticQuestion();};
  function renderDiagnosticQuestion(){const s=diagnosticState;if(!s)return;const page=ensurePage('s54DiagnosticPage'),q=s.items[s.index],choices=Array.isArray(q.choices)?q.choices:[];page.innerHTML=`<div class="s54-page s54-no-nav">${topbar(s.path==='qudrat'?'قياس القدرات':'قياس التحصيلي',`${s.index+1} من ${s.items.length}`,"s54AbortDiagnostic()")}
    <div class="s54-diag-progress"><i style="width:${pct(s.index,s.items.length)}%"></i></div><div class="s54-question"><div class="s54-question-meta"><span class="s54-chip">${esc(q.exam)}</span><span class="s54-chip">${esc(q.subject||q.category||q.skill||'عام')}</span></div><div class="s54-question-text">${esc(q.question)}</div><div class="s54-options">${choices.map((c,i)=>`<button class="s54-option ${s.selected===i?'selected':''}" onclick="s54SelectDiagnostic(${i})"><i>${['أ','ب','ج','د'][i]||i+1}</i><span>${esc(c)}</span></button>`).join('')}</div></div><button class="s54-primary s54-diag-next" ${s.selected==null?'disabled':''} onclick="s54NextDiagnostic()">${s.index===s.items.length-1?'عرض النتيجة':'التالي'}</button></div>`;setMode('exam');}
  window.s54SelectDiagnostic=function(i){if(!diagnosticState)return;diagnosticState.selected=i;renderDiagnosticQuestion();};
  window.s54NextDiagnostic=function(){const s=diagnosticState;if(!s||s.selected==null)return;s.answers.push(s.selected);s.selected=null;if(s.index<s.items.length-1){s.index++;renderDiagnosticQuestion();}else finishDiagnostic();};
  window.s54AbortDiagnostic=function(){if(confirm('الخروج من القياس؟ لن تحفظ الإجابات الحالية.')){diagnosticState=null;showPage('homePage');}};
  function syncDiagnosticResult(){/* Streamlit uses its local bank. The Expo client must use the server-issued diagnostic session so answers are graded on the server, never trust a client-supplied score. */}
  function finishDiagnostic(){const s=diagnosticState,p=getProfile(),groups={};let correct=0;s.items.forEach((q,i)=>{const ok=Number(s.answers[i])===Number(q.correct);if(ok)correct++;const group=s.path==='qudrat'?q.exam:(q.subject||'تحصيلي');groups[group]||(groups[group]={total:0,correct:0});groups[group].total++;if(ok)groups[group].correct++;});Object.values(groups).forEach(g=>g.percent=pct(g.correct,g.total));let weighted=0,model='tahsili_common';if(s.path==='qudrat'){const q=groups['قدرات كمي']?.percent||0,v=groups['قدرات لفظي']?.percent||0;model=p.academicTrack==='literary'?'qudrat_literary':'qudrat_scientific';const m=SCORE_CATALOG.models?.[model]||{};weighted=q*Number(m.quant_weight||.5)+v*Number(m.verbal_weight||.5);}else{const m=SCORE_CATALOG.models?.tahsili_common||{};weighted=(groups['رياضيات']?.percent||0)*Number(m.math_weight||.25)+(groups['فيزياء']?.percent||0)*Number(m.physics_weight||.25)+(groups['كيمياء']?.percent||0)*Number(m.chemistry_weight||.25)+(groups['أحياء']?.percent||0)*Number(m.biology_weight||.25);}const record={id:Date.now(),path:s.path,academicTrack:s.path==='qudrat'?p.academicTrack:null,model,total:s.items.length,correct,rawPercent:pct(correct,s.items.length),weightedPercent:Math.round(weighted),groups,date:new Date().toISOString(),elapsedSec:Math.round((Date.now()-s.startedAt)/1000)};const ds=diagnostics();ds[s.path]=record;write('diagnostics',ds);markActivity(`diagnostic_${s.path}`);syncDiagnosticResult(record,s.answers,s.items);s.finished=true;renderDiagnosticResult(record);}
  function renderDiagnosticResult(r){const page=ensurePage('s54DiagnosticPage'),weak=Object.entries(r.groups).sort((a,b)=>a[1].percent-b[1].percent)[0];page.innerHTML=`<div class="s54-page">${topbar(r.path==='qudrat'?'نتيجة قياس القدرات':'نتيجة قياس التحصيلي','محفوظة بشكل مستقل عن الاختبار الآخر',"showPage('homePage')")}<div class="s54-result-ring" style="--score:${r.weightedPercent}"><div><span>مؤشر الجاهزية</span><b>${r.weightedPercent}%</b></div></div><div class="s54-result-list">${Object.entries(r.groups).map(([n,g])=>`<div class="s54-result-row"><div class="top"><span>${esc(n)}</span><b>${g.percent}%</b></div><div class="bar"><i style="width:${g.percent}%"></i></div></div>`).join('')}</div><div class="s54-card" style="margin-top:10px"><b style="font-size:14px">أولوية البداية: ${esc(weak?.[0]||'التثبيت')}</b><div class="s54-subtitle">سيركز سهيل على هذا القسم في الخطة، من دون التأثير على سجل ${r.path==='qudrat'?'التحصيلي':'القدرات'}.</div></div><div class="s54-card" style="margin-top:9px"><b style="font-size:12px">تنبيه</b><div class="s54-subtitle">${esc(SCORE_CATALOG.disclaimer_ar||'مؤشر داخلي وليس درجة رسمية.')}</div></div><button class="s54-primary" style="width:100%;margin-top:12px" onclick="showPage('tasksPage')">ابدأ خطة اليوم</button></div>`;setMode('main');}

  /* Social prototype UI. Backend API included in Sprint 53; local fallback keeps preview usable. */
  function social(){return merge({friends:[],challenges:[],xp:0},read('social',{}));}
  function saveSocial(v){return write('social',v);}
  function renderChallenge(){const page=ensurePage('challengePage'),p=getProfile(),s=social(),templates=Array.isArray(CHALLENGE_CATALOG.templates)?CHALLENGE_CATALOG.templates:[];page.innerHTML=`<div class="s54-page">${topbar('تحدي الأصدقاء','منافسة قصيرة على الدقة والوقت',"showPage('homePage')")}<div class="s54-challenge-banner"><div><b>كودك: ${friendCode()}</b><span>شاركه مع صديق، وبعد قبول الطلب تستطيعان بدء تحدٍ متساوي.</span></div><div class="s54-trophy">${svg('trophy')}</div></div><div class="s54-section"><div class="s54-section-head"><b>إضافة صديق</b></div><div class="s54-card" style="display:flex;gap:8px"><input id="s54Friend" class="s54-input" placeholder="كود SH- أو اسم تجريبي"><button class="s54-primary" onclick="s54AddFriend()">إضافة</button></div></div><div class="s54-section"><div class="s54-section-head"><b>الأصدقاء</b></div>${s.friends.length?s.friends.map(f=>`<div class="s54-setting"><div class="main">${avatarHtml({avatarId:f.avatarId,displayName:f.name})}<div><b>${esc(f.name)}</b><small>${esc(f.code)} • ${f.xp||0} XP</small></div></div><button class="s54-link" onclick="s54PrepareChallenge('${esc(f.code)}')">تحدي</button></div>`).join(''):'<div class="s54-empty">لا يوجد أصدقاء بعد. في نسخة الخادم يمر الطلب بحالة إرسال ثم قبول.</div>'}</div><div class="s54-section"><div class="s54-section-head"><b>إنشاء تحدٍ</b></div><div class="s54-card"><div class="s54-form-grid"><div class="s54-field"><label>الصديق</label><select id="s54FriendSelect" class="s54-select"><option value="">اختر</option>${s.friends.map(f=>`<option value="${esc(f.code)}">${esc(f.name)}</option>`).join('')}</select></div><div class="s54-field"><label>نوع التحدي</label><select id="s54Template" class="s54-select">${templates.map(t=>`<option value="${esc(t.id)}">${esc(t.title)} • ${t.questions}</option>`).join('')}</select></div></div><button class="s54-primary" style="width:100%;margin-top:10px" onclick="s54CreateChallenge()">إرسال الدعوة</button></div></div><div class="s54-section"><div class="s54-section-head"><b>التحديات</b></div>${s.challenges.length?s.challenges.map(c=>`<div class="s54-setting"><div class="main"><span class="ico">${svg('trophy')}</span><div><b>${esc(c.friendName)} • ${esc(c.title)}</b><small>${c.questions} أسئلة • ${c.status==='active'?'نشط':'بانتظار القبول'}</small></div></div><span class="s54-chip">${c.status==='active'?'نشط':'مرسل'}</span></div>`).join(''):'<div class="s54-empty">بعد قبول صديقك للدعوة ستظهر النتيجة المشتركة هنا.</div>'}</div><div class="s54-note">الواجهة المحلية للمعاينة. Sprint 53 أضاف API لطلبات الصداقة والتحديات بتوقيت الخادم وحالات القبول.</div></div>`;setMode('main');}
  window.s54AddFriend=function(){const v=document.getElementById('s54Friend')?.value.trim();if(!v){toast('اكتب كود الصديق');return;}const s=social(),code=v.toUpperCase().startsWith('SH-')?v.toUpperCase():`SH-${String(hash(v)).slice(-6).padStart(6,'0')}`;if(code===friendCode()){toast('هذا كودك');return;}if(s.friends.some(f=>f.code===code)){toast('الصديق موجود');return;}const av=avatarItems();const a=av[hash(code)%Math.max(1,av.length)];s.friends.push({code,name:v.toUpperCase().startsWith('SH-')?`صديق ${code.slice(-3)}`:v,avatarId:a?.id||'male_01',xp:0,status:'accepted'});saveSocial(s);renderChallenge();toast('أضيف للمعاينة');};
  window.s54PrepareChallenge=function(code){renderChallenge();setTimeout(()=>{const e=document.getElementById('s54FriendSelect');if(e)e.value=code;},20);};
  window.s54CreateChallenge=function(){const s=social(),code=document.getElementById('s54FriendSelect')?.value,id=document.getElementById('s54Template')?.value,f=s.friends.find(x=>x.code===code),t=(CHALLENGE_CATALOG.templates||[]).find(x=>x.id===id);if(!f||!t){toast('اختر صديقًا ونوع التحدي');return;}s.challenges.unshift({id:Date.now(),friendCode:code,friendName:f.name,title:t.title,questions:t.questions,status:'pending',createdAt:Date.now()});saveSocial(s);renderChallenge();toast('تم إرسال الدعوة للمعاينة');};

  /* Deep admin: local draft + explicit API publish + audit trail. */
  function auditLog(){return parse(localStorage.getItem('s54_admin_audit')||'[]',[]);}
  function audit(action,detail){const a=auditLog();a.unshift({at:new Date().toISOString(),action,detail:detail||'',user:session()?.email||'local'});localStorage.setItem('s54_admin_audit',JSON.stringify(a.slice(0,100)));}
  function adminTabs(){const tabs=[['overview','نظرة عامة'],['journey','الرحلة'],['diagnostic','القياس'],['content','المحتوى'],['notify','الإشعارات'],['system','النظام']];return `<div class="s54-admin-tabs">${tabs.map(([id,n])=>`<button class="s54-admin-tab ${adminTab===id?'active':''}" onclick="s54AdminTab('${id}')">${n}</button>`).join('')}</div>`;}
  function field(path,label,type='number',note=''){const v=getPath(adminSettings(),path);return `<div class="s54-field"><label>${label}</label><input class="s54-input" type="${type}" value="${esc(v)}" onchange="s54AdminSet('${path}',this.value,'${type}')">${note?`<small>${esc(note)}</small>`:''}</div>`;}
  function toggle(path,label,note){const on=!!getPath(adminSettings(),path);return `<div class="s54-toggle"><div><b>${label}</b><small>${note||''}</small></div><button class="s54-switch ${on?'on':''}" onclick="s54AdminToggle('${path}')"><i></i></button></div>`;}
  function adminBody(){const s=adminSettings();if(adminTab==='overview'){const log=auditLog().slice(0,8);return `<div class="s54-admin-group"><h3>حالة الإعدادات</h3><p>التعديلات تحفظ كمسودة محلية. لا تصل للطلاب إلا بعد النشر إلى API بتوكن الأدمن.</p><div class="s54-facts"><div class="s54-fact"><b>${adminDraftDirty?'مسودة':'متزامن'}</b><span>حالة العمل</span></div><div class="s54-fact"><b>v${s.version||4}</b><span>نسخة الإعداد</span></div><div class="s54-fact"><b>54</b><span>الإصدار</span></div></div><div class="s54-admin-actions"><button class="s54-primary" onclick="s54AdminPublish()">نشر إلى API</button><button class="s54-secondary" onclick="s54AdminPull()">جلب من API</button><button class="s54-secondary" onclick="s54AdminExport()">تصدير</button></div></div><div class="s54-admin-group"><h3>سجل التغييرات</h3><p>آخر عمليات التعديل والنشر في هذه الجلسة.</p><div class="s54-audit-list">${log.length?log.map(x=>`<div class="s54-audit-row"><b>${esc(x.action)} • ${esc(x.detail)}</b><span>${new Date(x.at).toLocaleString('ar-SA')} • ${esc(x.user)}</span></div>`).join(''):'<div class="s54-empty">لا توجد تغييرات مسجلة بعد.</div>'}</div></div>`;}
    if(adminTab==='journey')return `<div class="s54-admin-group"><h3>رحلة الطالب اليومية</h3><p>زر واحد رئيسي وخطة قصيرة تتكيّف مع الأخطاء.</p><div class="s54-form-grid">${field('learning.daily_question_goal','هدف الأسئلة')}${field('learning.daily_error_goal','مراجعة الأخطاء')}${field('learning.daily_summary_goal','هدف الملخصات')}${field('learning.default_session_minutes','دقائق الجلسة')}</div>${toggle('learning.enable_prediction','مؤشر الجاهزية','يظهر كنطاق إرشادي لا كدرجة رسمية')}${toggle('learning.empty_state_guidance','الحالات الفارغة الذكية','توجيه الطالب بدل عرض الأصفار')}</div><div class="s54-admin-group"><h3>السلسلة اليومية</h3><p>تظهر الساعة الرملية خلال آخر ساعات قبل الانقطاع.</p>${toggle('streak.enabled','تفعيل الستريك','يحتاج نشاطًا تعليميًا')}${field('streak.rescue_window_hours','نافذة الإنقاذ بالساعات')}${toggle('streak.live_countdown','عداد حي','يتحدث كل دقيقة')}</div>`;
    if(adminTab==='diagnostic')return `<div class="s54-admin-group"><h3>تحديد مستوى القدرات</h3><p>يتغير فقط حسب المسار العلمي أو الأدبي.</p><div class="s54-form-grid">${field('diagnostic.qudrat_scientific.quant','كمي علمي')}${field('diagnostic.qudrat_scientific.verbal','لفظي علمي')}${field('diagnostic.qudrat_literary.quant','كمي أدبي')}${field('diagnostic.qudrat_literary.verbal','لفظي أدبي')}</div></div><div class="s54-admin-group"><h3>تحديد مستوى التحصيلي</h3><p>قياس واحد مستقل لا يتغير بمسار الطالب.</p><div class="s54-form-grid">${field('diagnostic.tahsili_common.math','رياضيات')}${field('diagnostic.tahsili_common.physics','فيزياء')}${field('diagnostic.tahsili_common.chemistry','كيمياء')}${field('diagnostic.tahsili_common.biology','أحياء')}</div>${toggle('diagnostic.separate_records','سجلات منفصلة','لا تختلط نتائج القدرات والتحصيلي')}${toggle('diagnostic.allow_both_exam_goals','السماح بالاختبارين','الطالب يختار أحدهما أو الاثنين')}</div>`;
    if(adminTab==='content')return `<div class="s54-admin-group"><h3>حوكمة الأسئلة والملخصات</h3><p>لا ينتقل المحتوى إلى النشر دون استكمال الحقول والاعتماد.</p>${toggle('content.require_reviewer_approval','اعتماد المراجع','مسودة ← مراجعة ← معتمد ← منشور')}${toggle('content.require_explanation','الشرح إلزامي','رفض السؤال بلا تفسير')}${toggle('content.require_skill_tag','المهارة إلزامية','لبناء تحليل وخطة دقيقة')}${toggle('content.require_source','المصدر إلزامي','يوصى بتفعيله قبل الإنتاج')}${field('content.duplicate_threshold','حد اكتشاف التكرار','number','0.8 افتراضي')}</div><div class="s54-admin-group"><h3>الأداء</h3><p>حجم الصفحات والكاش والتحميل المسبق.</p><div class="s54-form-grid">${field('performance.question_page_size','صفحة الأسئلة')}${field('performance.summary_page_size','صفحة الملخصات')}${field('performance.client_cache_minutes','كاش العميل')}${field('performance.initial_payload_target_kb','هدف التحميل KB')}</div>${toggle('performance.preload_next_question','تحميل السؤال التالي','تحسين الانتقال')}${toggle('performance.lazy_question_api','تحميل الأسئلة من API','مطلوب للإنتاج')}</div>`;
    if(adminTab==='notify')return `<div class="s54-admin-group"><h3>الإشعارات</h3><p>تعمل فعليًا بعد ربط Expo/APNs بالخادم.</p>${toggle('notifications.enabled','المفتاح الرئيسي','إيقاف جميع التنبيهات')}${toggle('notifications.daily_plan','خطة اليوم','تذكير جلسة اليوم')}${toggle('notifications.streak_warning','إنقاذ الستريك','الساعة الرملية')}${toggle('notifications.challenge_invites','دعوات التحدي','عند دعوة صديق')}${toggle('notifications.review_due','مراجعة مستحقة','التكرار المتباعد')}<div class="s54-form-grid">${field('notifications.quiet_hours_start','بداية الهدوء','text')}${field('notifications.quiet_hours_end','نهاية الهدوء','text')}</div></div>`;
    return `<div class="s54-admin-group"><h3>ربط API</h3><p>الافتراضي هو خادم الجهاز على المنفذ 5000.</p><div class="s54-form-grid"><div class="s54-field"><label>عنوان API</label><input id="s54ApiBase" class="s54-input" value="${esc(localStorage.getItem('s54_api_base')||`http://${location.hostname}:5000`)}"></div><div class="s54-field"><label>توكن الأدمن</label><input id="s54AdminToken" class="s54-input" type="password" value="${esc(localStorage.getItem('s54_admin_token')||'')}"></div></div><div class="s54-admin-actions"><button class="s54-primary" onclick="s54SaveApi()">حفظ الربط</button><button class="s54-secondary" onclick="s54TestApi()">اختبار الاتصال</button></div></div><div class="s54-admin-group"><h3>استيراد الإعدادات</h3><p>الصق JSON موثوقًا ثم راجعه قبل النشر.</p><textarea id="s54AdminJson" class="s54-textarea">${esc(JSON.stringify(s,null,2))}</textarea><div class="s54-admin-actions"><button class="s54-primary" onclick="s54AdminImport()">استيراد كمسودة</button><button class="s54-secondary" onclick="s54AdminReset()">استعادة الافتراضي</button></div></div>`;}
  function renderAdmin(){const page=ensurePage('adminSettingsPage');if(!isAdmin()){toast('هذه الصفحة للأدمن فقط');showPage('homePage');return;}page.innerHTML=`<div class="s54-page">${topbar('لوحة الأدمن','إدارة مركزية بمسودة ونشر وسجل تغييرات',"showPage('profilePage')")}${adminTabs()}${adminBody()}</div>`;setMode('main');}
  window.s54AdminTab=function(t){adminTab=t;renderAdmin();};
  window.s54AdminSet=function(path,value,type){const s=adminSettings(),v=type==='number'?Number(value):value;setPath(s,path,v);saveAdminSettings(s);adminDraftDirty=true;audit('تعديل',path);};
  window.s54AdminToggle=function(path){const s=adminSettings();setPath(s,path,!getPath(s,path));saveAdminSettings(s);adminDraftDirty=true;audit('تبديل',path);renderAdmin();};
  function apiBase(){return (localStorage.getItem('s54_api_base')||`http://${location.hostname}:5000`).replace(/\/$/,'');}
  window.s54SaveApi=function(){localStorage.setItem('s54_api_base',document.getElementById('s54ApiBase')?.value.trim()||'');localStorage.setItem('s54_admin_token',document.getElementById('s54AdminToken')?.value||'');toast('تم حفظ الربط');};
  window.s54TestApi=async function(){try{const r=await fetch(`${apiBase()}/health`);if(!r.ok)throw new Error();const d=await r.json();toast(`API متصل • ${d.release||'جاهز'}`);}catch(_){toast('تعذر الاتصال بـ API');}};
  window.s54AdminPublish=async function(){const token=localStorage.getItem('s54_admin_token')||'';if(!token){toast('أدخل توكن الأدمن من تبويب النظام');return;}try{const r=await fetch(`${apiBase()}/api/v1/admin/settings`,{method:'PUT',headers:{'Content-Type':'application/json','X-Suhail-Admin-Token':token},body:JSON.stringify(adminSettings())});if(!r.ok)throw new Error();adminDraftDirty=false;audit('نشر','الإعدادات إلى API');renderAdmin();toast('تم النشر إلى الخادم');}catch(_){toast('فشل النشر؛ بقيت المسودة محلية');}};
  window.s54AdminPull=async function(){const token=localStorage.getItem('s54_admin_token')||'';try{const r=await fetch(`${apiBase()}/api/v1/admin/settings`,{headers:{'X-Suhail-Admin-Token':token}});if(!r.ok)throw new Error();saveAdminSettings(await r.json());adminDraftDirty=false;audit('مزامنة','جلب من API');renderAdmin();toast('تم جلب الإعدادات');}catch(_){toast('تعذر جلب الإعدادات');}};
  window.s54AdminExport=function(){const blob=new Blob([JSON.stringify(adminSettings(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='suhail_admin_settings_s54.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);};
  window.s54AdminImport=function(){try{saveAdminSettings(merge(clone(DEFAULT_ADMIN),JSON.parse(document.getElementById('s54AdminJson').value)));adminDraftDirty=true;audit('استيراد','JSON كمسودة');renderAdmin();toast('تم الاستيراد كمسودة');}catch(_){toast('JSON غير صالح');}};
  window.s54AdminReset=function(){if(confirm('استعادة الإعدادات الافتراضية؟')){localStorage.removeItem('s54_admin_settings');adminDraftDirty=true;audit('استعادة','الإعدادات الافتراضية');renderAdmin();}};

  function patchNavigationEntrypoints(){
    if(typeof window.openSummaryUnit==='function'&&!window.__s54SummaryPatched){window.__s54SummaryPatched=true;const old=window.openSummaryUnit;window.openSummaryUnit=function(){const r=old.apply(this,arguments);setTimeout(()=>setMode('summary'),20);return r;};}
    ['openSummaryExam','openSummarySubject','openSummarySection','s28SummariesGateway'].forEach(name=>{if(typeof window[name]==='function'&&!window[`__s54_${name}`]){window[`__s54_${name}`]=true;const old=window[name];window[name]=function(){const r=old.apply(this,arguments);setTimeout(()=>setMode('main'),20);return r;};}});
    ['startExam','beginExamWithMode','restoreQuizView'].forEach(name=>{if(typeof window[name]==='function'&&!window[`__s54_${name}`]){window[`__s54_${name}`]=true;const old=window[name];window[name]=function(){const r=old.apply(this,arguments);setTimeout(()=>setMode('exam'),20);return r;};}});
    ['finishExam','resetExam','backToExamSetup'].forEach(name=>{if(typeof window[name]==='function'&&!window[`__s54_${name}`]){window[`__s54_${name}`]=true;const old=window[name];window[name]=function(){const r=old.apply(this,arguments);setTimeout(()=>setMode('main'),30);return r;};}});
    if(typeof window.answerQuiz==='function'&&!window.__s54AnswerPatched){window.__s54AnswerPatched=true;const old=window.answerQuiz;window.answerQuiz=function(){const r=old.apply(this,arguments);markActivity('answer');return r;};}
    if(typeof window.openSummaryUnit==='function'&&!window.__s54SummaryActivity){window.__s54SummaryActivity=true;const old=window.openSummaryUnit;window.openSummaryUnit=function(){const r=old.apply(this,arguments);markActivity('summary');setTimeout(()=>setMode('summary'),20);return r;};}
  }
  function patchShowPage(){if(window.__s54ShowPatched)return;window.__s54ShowPatched=true;legacyShowPage=typeof window.showPage==='function'?window.showPage.bind(window):null;window.showPage=function(id){if(id==='accountPage')id='profilePage';if(id==='friendsPage')id='challengePage';if(id==='s47DiagnosticPage')id='diagnosticChoicePage';if(id==='studentSetupPage'){activate(id);renderSetup();return;}if(id==='diagnosticChoicePage'){activate(id);renderDiagnosticChoice();return;}if(id==='s54DiagnosticPage'){activate(id);renderDiagnosticQuestion();return;}if(id==='challengePage'){activate(id);renderChallenge();return;}if(id==='adminSettingsPage'){activate(id);renderAdmin();return;}const result=legacyShowPage?legacyShowPage(id):activate(id);setTimeout(()=>{if(id==='homePage')renderHome();else if(id==='profilePage')renderProfile();else setMode(MAIN_PAGES.has(id)?'main':modeForPage(id));},80);return result;};window.s39OpenDiagnostic=()=>window.showPage('diagnosticChoicePage');window.s47OpenDiagnosticChoice=(p)=>window.s54OpenDiagnostic(p);}
  function patchLogin(){if(window.__s54LoginPatched||typeof window.loginUser!=='function')return;window.__s54LoginPatched=true;const old=window.loginUser;window.loginUser=function(){const r=old.apply(this,arguments);setTimeout(()=>{const p=getProfile();if(session()?.role==='student'&&!p.onboardingDone)showPage('studentSetupPage');else showPage('homePage');},130);return r;};}
  function installGuard(){const home=document.getElementById('homePage');if(home&&!window.__s54HomeGuard){window.__s54HomeGuard=true;new MutationObserver(()=>{if(guardBusy)return;if(home.classList.contains('active')&&!home.querySelector('[data-s54-home]'))setTimeout(renderHome,20);}).observe(home,{childList:true});}const auth=document.getElementById('authPage');if(auth&&!window.__s54AuthGuard){window.__s54AuthGuard=true;new MutationObserver(syncAuthMode).observe(auth,{attributes:true,attributeFilter:['class']});}setInterval(()=>{const p=activePage();if(p?.id==='homePage'&&!p.querySelector('[data-s54-home]'))renderHome();updateStreakElements();patchNavigationEntrypoints();syncAuthMode();},30000);}
  function install(){document.body.classList.add('s54-ready');['studentSetupPage','diagnosticChoicePage','s54DiagnosticPage','adminSettingsPage','challengePage'].forEach(ensurePage);ensureNav();patchShowPage();patchLogin();patchNavigationEntrypoints();installGuard();const p=activePage();if(p?.id==='homePage')renderHome();else if(p?.id==='profilePage')renderProfile();else setMode(modeForPage(p?.id||'homePage'));window.SUHAIL_RELEASE=VERSION;setInterval(updateStreakElements,60000);setTimeout(()=>{patchNavigationEntrypoints();updateStreakElements();},700);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
