/* Suhail Sprint 112 — friends by username; no messages or chat. */
(function(){
'use strict';
const VERSION='112.0.0';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const back='<svg viewBox="0 0 24 24"><path d="m9 5 7 7-7 7"/></svg>';
function base(){return (localStorage.getItem('s54_api_base')||`http://${location.hostname}:5000`).replace(/\/$/,'')}
function token(){return localStorage.getItem('suhail_api_token')||''}
function session(){try{return typeof getAuthSession==='function'?getAuthSession():JSON.parse(localStorage.getItem('suhail_auth_user')||'null')}catch(_){return null}}
function ensurePage(id){let p=document.getElementById(id);if(!p){p=document.createElement('div');p.id=id;p.className='page';document.querySelector('.content')?.appendChild(p)}return p}
function activate(id){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));document.querySelector('.content')?.scrollTo?.({top:0});document.body.classList.remove('s113-live');document.querySelectorAll('#s110BottomNav [data-s110-nav]').forEach(b=>b.classList.toggle('active',b.dataset.s110Nav==='account'))}
async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(token())headers.Authorization=`Bearer ${token()}`;const r=await fetch(`${base()}${path}`,{...options,headers});let data={};try{data=await r.json()}catch(_){}if(!r.ok){const e=new Error(data.error||`HTTP_${r.status}`);e.data=data;e.status=r.status;throw e}return data}
function errorText(code){return ({username_not_found:'اليوزر غير موجود',already_friends:'هذا المستخدم ضمن أصدقائك',request_exists:'طلب الصداقة مرسل مسبقًا',cannot_add_self:'لا يمكنك إضافة حسابك',authentication_required:'سجّل الدخول مرة أخرى',profile_required:'أكمل إعداد الحساب أولًا',invalid_credentials:'تعذر ربط الحساب بالخادم',rate_limited:'حاول بعد دقيقة',failed_fetch:'تعذر الاتصال بالخادم'})[code]||'تعذر إكمال العملية الآن'}
async function syncProfile(payload){try{await api('/api/v1/profile',{method:'PUT',body:JSON.stringify({display_name:payload.name||payload.display_name||'طالب سهيل',academic_track:'scientific',gender:payload.gender==='female'?'female':'male',exam_goals:['qudrat','tahsili'],avatar_id:payload.gender==='female'?'female_01':'male_02'})})}catch(_){}}
window.s112SyncApiRegister=async function(payload){try{const d=await api('/api/v1/auth/register',{method:'POST',body:JSON.stringify({email:payload.email,password:payload.password,display_name:payload.name,username:payload.username})});localStorage.setItem('suhail_api_token',d.token);await syncProfile(payload);return true}catch(e){if(e.status===409)return window.s112SyncApiLogin(payload.email,payload.password);return false}};
window.s112SyncApiLogin=async function(email,password){try{const d=await api('/api/v1/auth/login',{method:'POST',body:JSON.stringify({email,password})});localStorage.setItem('suhail_api_token',d.token);return true}catch(e){const s=session();if(s&&e.status===401){return window.s112SyncApiRegister({email,password,name:s.name,username:s.username,gender:s.gender})}return false}};
function top(title,sub){return `<div class="s112-top"><button class="s112-back" onclick="showPage('profilePage')" aria-label="العودة">${back}</button><div><h1>${esc(title)}</h1><p>${esc(sub)}</p></div></div>`}
async function load(){const page=ensurePage('friendsPage');activate('friendsPage');page.innerHTML=`<div class="s112-page">${top('الأصدقاء','إضافة باليوزر فقط — لا توجد رسائل')}<div class="s112-empty">جار تحميل قائمة الأصدقاء…</div></div>`;if(!token()){page.querySelector('.s112-empty').innerHTML='يلزم تسجيل الخروج ثم الدخول مرة أخرى لربط الأصدقاء بالخادم.';return}
try{const [friends,requests]=await Promise.all([api('/api/v1/friends'),api('/api/v1/friend-requests')]);render(friends.items||[],requests.incoming||[],requests.outgoing||[])}catch(e){render([],[],[],errorText(e.message))}}
function render(friends,incoming,outgoing,error=''){const p=ensurePage('friendsPage');const online=!!token()&&!error;p.innerHTML=`<div class="s112-page">${top('الأصدقاء','أضف الطالب أولًا ثم ادعه من التحديات')}
<section class="s112-card"><div style="display:flex;align-items:center;justify-content:space-between;gap:8px"><h2>إضافة صديق</h2><span class="s112-connection ${online?'online':''}"><i></i>${online?'متصل':'غير متصل'}</span></div><p>اكتب اليوزر كما يظهر في حساب صديقك. لا توجد محادثات أو رسائل.</p><div class="s112-add"><input id="s112Username" class="s112-input" maxlength="20" placeholder="username" autocomplete="off"><button class="s112-primary" onclick="s112SendRequest()">إرسال طلب</button></div><div id="s112Status" class="s112-status ${error?'err':''}">${esc(error)}</div></section>
${incoming.length?`<div class="s112-section-title"><b>طلبات وصلتني</b><span>${incoming.length}</span></div><div class="s112-list">${incoming.map(r=>person(r.sender_name||'طالب سهيل',r.sender_username||r.sender_code,r.sender_code,`<button class="s112-action accept" onclick="s112Respond(${Number(r.id)},'accept')">قبول</button><button class="s112-action reject" onclick="s112Respond(${Number(r.id)},'decline')">رفض</button>`)).join('')}</div>`:''}
<div class="s112-section-title"><b>قائمة الأصدقاء</b><span>${friends.length} أصدقاء</span></div><div class="s112-list">${friends.length?friends.filter(f=>!f.blocked).map(f=>person(f.friend_name,f.username||f.friend_code,f.friend_code,`<button class="s112-action challenge" onclick="s113OpenCreate('${esc(f.friend_code)}')">دعوة</button><button class="s112-action block" onclick="s112Safety('${esc(f.friend_code)}','${esc(f.friend_name)}')">•••</button>`)).join(''):'<div class="s112-empty">لا يوجد أصدقاء بعد. أضفهم باليوزر أولًا.</div>'}</div>
${outgoing.length?`<div class="s112-section-title"><b>طلبات مرسلة</b><span>${outgoing.length}</span></div><div class="s112-list">${outgoing.slice(0,5).map(r=>person('طلب صداقة',r.receiver_code,r.receiver_code,'<span style="font-size:9px;color:var(--s110-muted)">بانتظار القبول</span>')).join('')}</div>`:''}</div>`;activate('friendsPage')}
function person(name,username,code,actions){const first=String(name||'س').trim().charAt(0)||'س';return `<article class="s112-person"><div class="s112-avatar">${esc(first)}</div><div class="s112-person-copy"><b>${esc(name)}</b><span>@${esc(String(username||code).replace(/^@/,''))}</span></div><div class="s112-actions">${actions}</div></article>`}
window.s112OpenFriends=load;
window.s112SendRequest=async function(){const input=document.getElementById('s112Username'),status=document.getElementById('s112Status'),username=String(input?.value||'').trim().toLowerCase().replace(/^@/,'');if(!/^[a-z0-9_]{3,20}$/.test(username)){status.className='s112-status err';status.textContent='اكتب يوزر صحيحًا من 3 إلى 20 خانة';return}status.className='s112-status';status.textContent='جار إرسال الطلب…';try{await api('/api/v1/friend-requests',{method:'POST',body:JSON.stringify({receiver_username:username})});status.className='s112-status ok';status.textContent='تم إرسال طلب الصداقة';input.value='';setTimeout(load,500)}catch(e){status.className='s112-status err';status.textContent=errorText(e.message)}};
window.s112Respond=async function(id,action){try{await api(`/api/v1/friend-requests/${id}/respond`,{method:'POST',body:JSON.stringify({action})});load()}catch(e){alert(errorText(e.message))}};
window.s112Safety=async function(code,name){const choice=prompt(`إدارة ${name}\nاكتب 1 للحظر أو 2 للإبلاغ عن يوزر غير مناسب`);if(choice==='1'){if(confirm('سيختفي هذا الصديق ولن يتمكن من دعوتك. متابعة؟')){try{await api('/api/v1/blocks',{method:'POST',body:JSON.stringify({friend_code:code})});load()}catch(e){alert(errorText(e.message))}}}else if(choice==='2'){const reason=prompt('اكتب سبب البلاغ باختصار','اسم أو يوزر غير مناسب');if(reason){try{await api('/api/v1/reports',{method:'POST',body:JSON.stringify({friend_code:code,reason})});alert('تم استلام البلاغ')}catch(e){alert(errorText(e.message))}}}};
window.SuhailFriends112={version:VERSION,api,base,token,load};window.SUHAIL_RELEASE=VERSION;document.documentElement.dataset.suhailRelease=VERSION;
})();
