/* Suhail Sprint 114 — complete in-app terms/privacy, deletion and final wiring. */
(function(){
'use strict';
const VERSION='114.0.0';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const back='<svg viewBox="0 0 24 24"><path d="m9 5 7 7-7 7"/></svg>';
function ensurePage(){let p=document.getElementById('s114LegalPage');if(!p){p=document.createElement('div');p.id='s114LegalPage';p.className='page';document.querySelector('.content')?.appendChild(p)}return p}
function activate(){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id==='s114LegalPage'));document.querySelector('.content')?.scrollTo?.({top:0});document.body.classList.remove('s113-live');document.querySelectorAll('#s110BottomNav [data-s110-nav]').forEach(b=>b.classList.toggle('active',b.dataset.s110Nav==='account'))}
function top(title,sub,backAction="showPage('profilePage')"){return `<div class="s114-top"><button class="s114-back" onclick="${backAction}" aria-label="العودة">${back}</button><div><h1>${esc(title)}</h1><p>${esc(sub)}</p></div></div>`}
window.s114OpenLegal=function(){const p=ensurePage();p.innerHTML=`<div class="s114-page">${top('الخصوصية والشروط','وثائق التطبيق وإدارة الحساب')}<div class="s114-menu"><button onclick="s114OpenTerms()"><b>شروط الاستخدام</b><span>الاستخدام، التحديات والمحتوى</span></button><button onclick="s114OpenPrivacy()"><b>سياسة الخصوصية</b><span>البيانات، الأصدقاء والحذف</span></button></div><section class="s114-delete"><b>حذف الحساب</b><p>يحذف الحساب ونتائج التعلم وعلاقات الصداقة وبيانات التحديات المرتبطة، عدا ما يلزم الاحتفاظ به نظامًا.</p><button onclick="s114DeleteAccount()">بدء حذف الحساب</button></section></div>`;activate()};
window.s114OpenTerms=function(){const p=ensurePage();p.innerHTML=`<div class="s114-page">${top('شروط الاستخدام','آخر تحديث: 25 يونيو 2026',"s114OpenLegal()") }<article class="s114-doc"><span class="s114-updated">آخر تحديث: 25 يونيو 2026</span><p>باستخدام تطبيق سهيل أو إنشاء حساب فيه، فإنك توافق على هذه الشروط.</p><h2>1. الخدمة</h2><p>سهيل تطبيق تعليمي يقدم ملخصات وتجميعات واختبارات وتقارير أداء وخطوات مراجعة مقترحة، إضافة إلى تحديات اختبارية بين الأصدقاء. لا توجد رسائل أو محادثات بين المستخدمين.</p><h2>2. الحساب</h2><p>يجب تقديم معلومات صحيحة والمحافظة على سرية بيانات الدخول. اليوزر فريد ويستخدم للبحث وإرسال طلبات الصداقة والدعوات للاختبارات فقط.</p><h2>3. الاستخدام التعليمي</h2><p>الدرجات ومؤشرات الجاهزية والتوصيات داخل سهيل تقديرات تعليمية مبنية على نشاط المستخدم، وليست نتائج رسمية أو ضمانًا لدرجة في أي اختبار خارجي.</p><h2>4. الأصدقاء والتحديات</h2><p>لا يمكن دعوة مستخدم إلى تحدٍ إلا بعد قبول طلب الصداقة. الحد الأقصى 10 لاعبين شامل المنشئ. الوقت ثابت 30 ثانية، وأول إجابة صحيحة معتمدة من الخادم تحصل على النقطة وتنقل الجميع للسؤال التالي.</p><h2>5. الاستخدام الممنوع</h2><p>يمنع الغش، استخدام يوزر مسيء أو منتحل، الوصول غير المصرح به، نسخ المحتوى أو إعادة توزيعه، تعطيل الخدمة، أو استخدام وسائل آلية للتأثير في النتائج.</p><h2>6. الملكية والمحتوى</h2><p>المحتوى والتصاميم والبرمجيات داخل سهيل للاستخدام الشخصي التعليمي فقط، ولا يجوز نسخها أو بيعها أو إعادة نشرها دون تصريح.</p><h2>7. الاشتراكات</h2><p>عند تفعيل الاشتراكات، تظهر المدة والسعر قبل الشراء، وتخضع عمليات الدفع والاسترداد لشروط متجر Apple والأنظمة المطبقة.</p><h2>8. التعليق والحذف</h2><p>يجوز تقييد الحساب عند مخالفة الشروط أو الإضرار بالخدمة. يستطيع المستخدم بدء حذف حسابه من داخل صفحة الحساب.</p><h2>9. حدود الخدمة</h2><p>نسعى لدقة المحتوى واستمرارية الخدمة، لكن قد تقع أخطاء أو انقطاعات. لا يعتمد على مؤشر الجاهزية وحده لاتخاذ قرار تعليمي مصيري.</p><h2>10. التواصل</h2><p>قد تتحدث الشروط عند تطوير الخدمة. للاستفسارات: eng.mb.alharbi@gmail.com</p></article></div>`;activate()};
window.s114OpenPrivacy=function(){const p=ensurePage();p.innerHTML=`<div class="s114-page">${top('سياسة الخصوصية','آخر تحديث: 25 يونيو 2026',"s114OpenLegal()") }<article class="s114-doc"><span class="s114-updated">آخر تحديث: 25 يونيو 2026</span><h2>1. البيانات التي نعالجها</h2><ul><li>الاسم والبريد واليوزر وكلمة المرور المشفرة ونوع الحساب.</li><li>الإجابات والنتائج والزمن والأخطاء والتقدم ومؤشرات الأداء.</li><li>طلبات الصداقة والدعوات والمشاركون والنقاط وأزمنة التحدي.</li><li>البلاغات والحظر وملاحظات الدعم والبيانات التقنية الضرورية.</li></ul><p>لا توجد رسائل أو محادثات بين المستخدمين، ولا يجمع سهيل محتوى دردشة.</p><h2>2. أغراض الاستخدام</h2><p>تشغيل الحساب، حساب الأداء، تقديم التوصيات، تشغيل التحديات بعدالة، حماية الخدمة، معالجة البلاغات وتحسين الاستقرار.</p><h2>3. المشاركة</h2><p>لا نبيع البيانات الشخصية للمعلنين. قد تعالج البيانات لدى مزودي خدمات تقنية بالقدر الضروري لتشغيل سهيل أو عند وجود التزام نظامي صحيح.</p><h2>4. ما يظهر للأصدقاء</h2><p>يظهر الاسم واليوزر داخل قائمة الأصدقاء والتحدي، وتظهر نتائج وترتيب التحدي للمشاركين في الغرفة نفسها. لا يظهر البريد الإلكتروني.</p><h2>5. الاحتفاظ والحذف</h2><p>نحتفظ بالبيانات ما دام الحساب فعالًا أو بقدر ما يلزم لتشغيل الخدمة والالتزامات النظامية. يستطيع المستخدم بدء حذف الحساب من داخل التطبيق.</p><h2>6. الأمان</h2><p>نستخدم كلمات مرور مشفرة ورموز جلسات وتحققًا خادميًا من توقيت وإجابات التحديات، مع العلم أنه لا توجد وسيلة تخزين أو نقل تضمن أمانًا مطلقًا.</p><h2>7. القاصرون</h2><p>يجب استخدام التطبيق بموافقة ولي الأمر عندما تتطلب الأنظمة ذلك، وعدم إدخال بيانات غير لازمة في الاسم أو اليوزر.</p><h2>8. الحقوق والتواصل</h2><p>يمكن تصحيح الحساب وحظر مستخدم وتقديم بلاغ وطلب الحذف. للاستفسارات: eng.mb.alharbi@gmail.com</p></article></div>`;activate()};
window.s114DeleteAccount=async function(){const confirmWord=prompt('لحذف الحساب نهائيًا اكتب: حذف');if(confirmWord!=='حذف')return;try{await window.SuhailFriends112.api('/api/v1/account',{method:'DELETE'});localStorage.removeItem('suhail_api_token');localStorage.removeItem('suhail_auth_user');alert('تم حذف الحساب والبيانات المرتبطة');if(typeof applyAuthState==='function')applyAuthState();else location.reload()}catch(e){alert('تعذر حذف الحساب الآن. تأكد من الاتصال ثم حاول مرة أخرى.')}};
function addConsent(){const pane=document.getElementById('registerPane');if(!pane||document.getElementById('s114Consent'))return;const target=pane.querySelector('.auth-submit,.auth-primary,button[onclick*="registerUser"]')||pane.lastElementChild;const box=document.createElement('div');box.id='s114Consent';box.className='s114-consent';box.innerHTML='<label><input id="s114ConsentCheck" type="checkbox"><span>أوافق على <a onclick="event.preventDefault();s114OpenTerms()">شروط الاستخدام</a> و<a onclick="event.preventDefault();s114OpenPrivacy()">سياسة الخصوصية</a>.</span></label>';target?.parentNode?.insertBefore(box,target)}
function wrapRegister(){if(window.__s114RegisterWrapped||typeof window.registerUser!=='function')return;window.__s114RegisterWrapped=true;const old=window.registerUser;window.registerUser=function(){if(!document.getElementById('s114ConsentCheck')?.checked){if(typeof showAuthMessage==='function')showAuthMessage('error','وافق على شروط الاستخدام وسياسة الخصوصية أولًا');return}return old.apply(this,arguments)}}
function install(){addConsent();wrapRegister();setTimeout(()=>{addConsent();wrapRegister()},500);window.SuhailLegal114={version:VERSION};window.SUHAIL_RELEASE=VERSION;document.documentElement.dataset.suhailRelease=VERSION}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
