/* Suhail Sprint 102 — PDF summary reader and admin file manager. */
(function(){
'use strict';
const VERSION='102.0.0';
const PAGES=__S102_PHYSICS1_PAGES__;
const KEY='suhail_pdf_marks_physics1_v1';
const COLORS=['#ffe66d','#83e6a2','#79c8ff','#ff9fc7'];
let color=COLORS[0], marking=false, erasing=false, draft=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function host(){return document.getElementById('summariesPage')}
function marks(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch(_){return[]}}
function save(list){localStorage.setItem(KEY,JSON.stringify(list))}
function back(){document.body.classList.remove('s102-reader-active');const p=host();if(p)p.classList.remove('s102-reader-host');window.SuhailSummaries101?.renderStages?.('فيزياء')}
function renderMarks(){const all=marks();document.querySelectorAll('.s102-highlight-layer').forEach(l=>{const n=Number(l.dataset.page);l.innerHTML=all.filter(x=>x.page===n).map(x=>`<i class="s102-highlight" data-id="${esc(x.id)}" style="left:${x.x}%;top:${x.y}%;width:${x.w}%;height:${x.h}%;background:${x.color}"></i>`).join('')})}
function setPageIndicator(){const r=document.querySelector('.s102-reader');if(!r)return;const pages=[...document.querySelectorAll('.s102-page')];let best=0,dist=1e9;pages.forEach((p,i)=>{const d=Math.abs(p.getBoundingClientRect().top-70);if(d<dist){dist=d;best=i}});const e=document.querySelector('.s102-page-indicator');if(e)e.textContent=`${best+1} / ${pages.length}`;localStorage.setItem('suhail_pdf_last_physics1',String(best+1))}
function open(){const p=host();if(!p)return;document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x===p));p.className='page active s102-reader-host';document.body.classList.add('s102-reader-active');p.innerHTML=`<div class="s102-reader"><button class="s102-reader-back" aria-label="رجوع"><svg viewBox="0 0 24 24"><path d="m15 18-6-6 6-6"/></svg></button><button class="s102-tools-toggle" aria-label="أدوات التظليل">🖍️</button><div class="s102-tools">${COLORS.map((c,i)=>`<button class="s102-color ${i===0?'active':''}" data-color="${c}" style="background:${c}" aria-label="لون تظليل"></button>`).join('')}<button class="s102-eraser">مسح</button></div><div class="s102-pages">${PAGES.map((src,i)=>`<section class="s102-page" data-page="${i+1}"><img src="${src}" alt="صفحة ${i+1} من ملخص فيزياء 1"><div class="s102-highlight-layer" data-page="${i+1}"></div></section>`).join('')}</div><div class="s102-page-indicator">1 / ${PAGES.length}</div></div>`;
 const reader=p.querySelector('.s102-reader');p.querySelector('.s102-reader-back').onclick=back;p.querySelector('.s102-tools-toggle').onclick=()=>p.querySelector('.s102-tools').classList.toggle('open');
 p.querySelectorAll('.s102-color').forEach(b=>b.onclick=()=>{color=b.dataset.color;marking=true;erasing=false;p.querySelectorAll('.s102-color').forEach(x=>x.classList.toggle('active',x===b));p.querySelectorAll('.s102-page').forEach(x=>x.classList.add('is-marking'))});
 p.querySelector('.s102-eraser').onclick=()=>{erasing=!erasing;marking=false;p.querySelectorAll('.s102-page').forEach(x=>x.classList.toggle('is-marking',erasing));p.querySelector('.s102-eraser').textContent=erasing?'اضغط على التظليل':'مسح'};
 p.querySelectorAll('.s102-page').forEach(pg=>{pg.addEventListener('pointerdown',start);pg.addEventListener('pointermove',move);pg.addEventListener('pointerup',end);pg.addEventListener('pointercancel',end)});
 p.addEventListener('click',e=>{const h=e.target.closest('.s102-highlight');if(h&&erasing){save(marks().filter(x=>x.id!==h.dataset.id));renderMarks()}});
 reader.addEventListener('scroll',setPageIndicator,{passive:true});renderMarks();const last=Math.max(1,Number(localStorage.getItem('suhail_pdf_last_physics1')||1));setTimeout(()=>p.querySelector(`.s102-page[data-page="${last}"]`)?.scrollIntoView(),60)
}
function point(ev,pg){const r=pg.getBoundingClientRect();return{x:Math.max(0,Math.min(100,(ev.clientX-r.left)/r.width*100)),y:Math.max(0,Math.min(100,(ev.clientY-r.top)/r.height*100))}}
function start(ev){if(!marking)return;ev.preventDefault();this.setPointerCapture?.(ev.pointerId);const q=point(ev,this);draft={page:Number(this.dataset.page),sx:q.x,sy:q.y,x:q.x,y:q.y,w:0,h:0,color,id:'m'+Date.now()+Math.random().toString(16).slice(2)};const el=document.createElement('i');el.className='s102-highlight';el.dataset.draft='1';el.style.cssText=`left:${q.x}%;top:${q.y}%;width:0;height:0;background:${color}`;this.querySelector('.s102-highlight-layer').appendChild(el)}
function move(ev){if(!draft||Number(this.dataset.page)!==draft.page)return;ev.preventDefault();const q=point(ev,this);draft.x=Math.min(draft.sx,q.x);draft.y=Math.min(draft.sy,q.y);draft.w=Math.abs(q.x-draft.sx);draft.h=Math.abs(q.y-draft.sy);const el=this.querySelector('[data-draft]');if(el)el.style.cssText=`left:${draft.x}%;top:${draft.y}%;width:${draft.w}%;height:${draft.h}%;background:${draft.color}`}
function end(){if(!draft)return;if(draft.w>1&&draft.h>.35){const a=marks();a.push({page:draft.page,x:+draft.x.toFixed(3),y:+draft.y.toFixed(3),w:+draft.w.toFixed(3),h:+draft.h.toFixed(3),color:draft.color,id:draft.id});save(a)}draft=null;renderMarks()}
function capture(e){const b=e.target.closest('[data-s101-action]');if(!b)return;const a=decodeURIComponent(b.dataset.s101Action||'');if(a==='stage::فيزياء::فيزياء 1'||a==='stage::%D9%81%D9%8A%D8%B2%D9%8A%D8%A7%D8%A1::%D9%81%D9%8A%D8%B2%D9%8A%D8%A7%D8%A1%201'){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();open()}}
function admin(){const box=document.getElementById('qmCleanContent');if(!box)return;const books=['فيزياء 1','فيزياء 2','فيزياء 3-1','فيزياء 3-2','كيمياء 1','كيمياء 2-1','كيمياء 2-2','كيمياء 3','رياضيات','الأحياء وعلم البيئة'];const html=books.map(b=>`<div class="s102-admin-pdf"><span class="s102-current-badge">${b==='فيزياء 1'?'مركّب حاليًا — 18 صفحة':'بانتظار الملف'}</span><h3>${b}</h3><p>ارفع ملف PDF واحدًا ليكون ملخص الكتاب كاملًا في وضع القراءة.</p><input type="file" accept="application/pdf" data-s102-upload="${esc(b)}"><div class="s102-pdf-status"></div></div>`).join('');window.qmAppSetPageHeading?.('ملفات الملخصات PDF','إدارة ملف واحد لكل كتاب أو مادة.');box.innerHTML=`<div class="app-admin-shell"><button class="app-admin-back" onclick="qmAppRenderContentHome()">رجوع لإدارة المحتوى</button><div class="app-admin-hero"><div class="app-admin-kicker">ملفات الملخصات</div><div class="app-admin-title">إدارة ملفات PDF</div><div class="app-admin-sub">كل كتاب يفتح للطالب بصفحة كاملة مع حفظ موضع القراءة والتظليل.</div></div><div class="s102-admin-grid">${html}</div></div>`;box.querySelectorAll('[data-s102-upload]').forEach(inp=>inp.onchange=()=>{const f=inp.files?.[0],s=inp.parentElement.querySelector('.s102-pdf-status');if(!f)return;s.textContent=`تم اختيار ${f.name} — جاهز للرفع والحفظ عند ربط الخادم.`})}
function install(){document.addEventListener('click',capture,true);window.s102OpenPhysics1=open;window.qmAppRenderSummaryCurricula=admin;window.SuhailPdfReader102={version:VERSION,open,back};window.SUHAIL_RELEASE=VERSION;document.documentElement.dataset.suhailRelease=VERSION}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
